# Generated by Django 6.0.3 on 2026-05-03 17:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Öffentliche ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Bezeichnung')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('icon', models.CharField(blank=True, default='bi-shield-check', help_text='z.B. „bi-shield-check", „bi-fire", „bi-bandaid".', max_length=50, verbose_name='Bootstrap-Icon')),
                ('recurrence', models.CharField(choices=[('rolling', 'Rollierend (N Monate ab Teilnahme)'), ('one_time', 'Einmalig (läuft nie ab)'), ('fixed', 'Fester Stichtag (z.B. jährlich zum 31.01.)')], default='rolling', help_text='Bestimmt, wie das Ablaufdatum berechnet wird.', max_length=20, verbose_name='Wiederholung')),
                ('validity_months', models.PositiveSmallIntegerField(default=12, help_text='Nur bei „Rollierend" relevant: nach dieser Zeit gilt die Teilnahme als abgelaufen.', verbose_name='Gültigkeitsdauer (Monate)')),
                ('fixed_deadline_month', models.PositiveSmallIntegerField(blank=True, help_text='Nur bei „Fester Stichtag": Monat (1=Januar, 12=Dezember).', null=True, verbose_name='Stichtag-Monat')),
                ('fixed_deadline_day', models.PositiveSmallIntegerField(blank=True, help_text='Nur bei „Fester Stichtag": Tag im Monat (z.B. 31).', null=True, verbose_name='Stichtag-Tag')),
                ('fixed_recurrence_years', models.PositiveSmallIntegerField(default=1, help_text='Nur bei „Fester Stichtag": meist 1 (jährlich) oder 2 (alle 2 Jahre).', verbose_name='Wiederholung alle X Jahre')),
                ('reminder_days_before', models.PositiveSmallIntegerField(default=30, help_text='Steuert, ab wann der Status „bald ablaufend" gilt und Erinnerungen versendet werden. Bei einmaligen Schulungen ohne Wirkung.', verbose_name='Erinnerung X Tage vor Ablauf')),
                ('is_mandatory', models.BooleanField(default=True, help_text='Wenn deaktiviert: optional (zählt nicht in die Compliance-Quote).', verbose_name='Pflichtschulung')),
                ('applies_to_all_students', models.BooleanField(default=True, help_text='Wenn deaktiviert: gilt nur für die unten ausgewählten Berufsbilder.', verbose_name='Gilt für alle Berufsbilder')),
                ('active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'Schulungs-Typ',
                'verbose_name_plural': 'Schulungs-Typen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Öffentliche ID')),
                ('completed_on', models.DateField(verbose_name='Absolviert am')),
                ('expires_on', models.DateField(blank=True, help_text='Wird automatisch aus „Absolviert am" + Schulungs-Typ-Konfiguration berechnet. Bei einmaligen Schulungen leer (lebenslang gültig).', null=True, verbose_name='Gültig bis')),
                ('certificate_paperless_id', models.IntegerField(blank=True, help_text='Optional: ID des hochgeladenen Zertifikats in Paperless.', null=True, verbose_name='Paperless-Dokument-ID')),
                ('notes', models.TextField(blank=True, verbose_name='Anmerkungen')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Erfasst am')),
                ('reminder_30_sent', models.BooleanField(default=False, verbose_name='Erinnerung T-30 versendet')),
                ('reminder_7_sent', models.BooleanField(default=False, verbose_name='Erinnerung T-7 versendet')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_training_completions', to=settings.AUTH_USER_MODEL, verbose_name='Erfasst von')),
            ],
            options={
                'verbose_name': 'Schulungs-Teilnahme',
                'verbose_name_plural': 'Schulungs-Teilnahmen',
                'ordering': ['-completed_on', 'training_type__name'],
            },
        ),
    ]
