# Generated by Django 6.0.3 on 2026-05-03 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0002_initial'),
        ('mandatorytraining', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcompletion',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_completions', to='student.student', verbose_name='Nachwuchskraft'),
        ),
        migrations.AddField(
            model_name='trainingtype',
            name='applies_to_job_profiles',
            field=models.ManyToManyField(blank=True, help_text='Greift nur, wenn „Gilt für alle Berufsbilder" deaktiviert ist.', related_name='mandatory_training_types', to='course.jobprofile', verbose_name='Berufsbilder'),
        ),
        migrations.AddField(
            model_name='trainingcompletion',
            name='training_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completions', to='mandatorytraining.trainingtype', verbose_name='Schulungs-Typ'),
        ),
        migrations.AddIndex(
            model_name='trainingcompletion',
            index=models.Index(fields=['student', 'training_type', '-completed_on'], name='mandatorytr_student_6ae1ae_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingcompletion',
            index=models.Index(fields=['expires_on'], name='mandatorytr_expires_a7b7a0_idx'),
        ),
    ]
