# Generated by Django 6.0.3 on 2026-05-03 17:50

import django.db.models.deletion
import services.storage
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KBCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Öffentliche ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('icon', models.CharField(default='bi-folder', help_text='z. B. bi-folder, bi-file-earmark-text, bi-info-circle', max_length=60, verbose_name='Bootstrap-Icon-Klasse')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Reihenfolge')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorien',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KBDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Öffentliche ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('file', models.FileField(blank=True, null=True, upload_to=services.storage.uuid_upload_to('knowledge/documents/'), verbose_name='Datei')),
                ('filename', models.CharField(blank=True, max_length=255, verbose_name='Dateiname')),
                ('external_url', models.URLField(blank=True, verbose_name='Externe URL')),
                ('content', models.TextField(blank=True, verbose_name='Textinhalt')),
                ('visibility', models.CharField(choices=[('all', 'Alle Nachwuchskräfte'), ('job_profile', 'Bestimmtes Berufsbild'), ('course', 'Bestimmter Kurs'), ('career', 'Bestimmte Laufbahn')], default='all', max_length=20, verbose_name='Sichtbarkeit')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Reihenfolge')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Geändert am')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='knowledge.kbcategory', verbose_name='Kategorie')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('target_career', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='course.career', verbose_name='Ziel-Laufbahn')),
                ('target_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='course.course', verbose_name='Ziel-Kurs')),
                ('target_job_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='course.jobprofile', verbose_name='Ziel-Berufsbild')),
            ],
            options={
                'verbose_name': 'Dokument',
                'verbose_name_plural': 'Dokumente',
                'ordering': ['category__order', 'category__name', 'order', 'title'],
            },
        ),
    ]
