# Generated by Django 6.0.3 on 2026-05-03 17:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Öffentliche ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token')),
                ('token_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Token gesendet am')),
                ('reminder_count', models.PositiveSmallIntegerField(default=0, help_text='Wie oft eine automatische Erinnerung an den Praxistutor gesendet wurde.', verbose_name='Anzahl Erinnerungen')),
                ('last_reminder_at', models.DateTimeField(blank=True, null=True, verbose_name='Letzte Erinnerung am')),
                ('escalated_at', models.DateTimeField(blank=True, help_text='Zeitpunkt der Eskalation an die zuständige Ausbildungskoordination.', null=True, verbose_name='Eskaliert am')),
                ('assessor_name', models.CharField(blank=True, max_length=200, verbose_name='Name des Praxistutors')),
                ('assessor_email', models.CharField(blank=True, max_length=254, verbose_name='E-Mail des Praxistutors')),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('submitted', 'Eingereicht'), ('confirmed', 'Bestätigt')], default='pending', max_length=20, verbose_name='Status')),
                ('overall_comment', models.TextField(blank=True, verbose_name='Gesamtkommentar')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eingereicht am')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Bestätigt am')),
            ],
            options={
                'verbose_name': 'Stationsbeurteilung',
                'verbose_name_plural': 'Stationsbeurteilungen',
                'ordering': ['-assignment__end_date'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Kriterium')),
                ('category', models.CharField(blank=True, help_text='Optionale Gruppierung, z.B. „Fachkompetenz" oder „Sozialkompetenz".', max_length=100, verbose_name='Kategorie')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('help_text', models.TextField(blank=True, help_text='Erläuterung für Praxistutoren und Auszubildende.', verbose_name='Hinweistext')),
            ],
            options={
                'verbose_name': 'Beurteilungskriterium',
                'verbose_name_plural': 'Beurteilungskriterien',
                'ordering': ['job_profile', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Notenwert (z.B. „2,3") oder Punktzahl (z.B. „12").', max_length=20, verbose_name='Bewertung')),
                ('comment', models.TextField(blank=True, verbose_name='Kommentar')),
            ],
            options={
                'verbose_name': 'Kriteriumbewertung',
                'verbose_name_plural': 'Kriteriumbewertungen',
            },
        ),
        migrations.CreateModel(
            name='AssessmentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('rating_scale', models.CharField(choices=[('grade', 'Notenskala (1,0–6,0)'), ('points', 'Punkteskala (0–15)')], max_length=20, verbose_name='Bewertungsskala')),
                ('instructions_assessor', models.TextField(blank=True, help_text='Wird im Beurteilungsformular für Praxistutoren angezeigt.', verbose_name='Hinweise für Praxistutoren')),
                ('instructions_self', models.TextField(blank=True, help_text='Wird im Portal-Formular für Auszubildende angezeigt.', verbose_name='Hinweise für Selbstbeurteilung')),
                ('active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Beurteilungsvorlage',
                'verbose_name_plural': 'Beurteilungsvorlagen',
                'ordering': ['job_profile', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentTemplateCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
            ],
            options={
                'verbose_name': 'Vorlagen-Kriterium',
                'verbose_name_plural': 'Vorlagen-Kriterien',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CriterionCompetenceWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, help_text='1.0 = volles Gewicht. Niedrigere Werte für teilweise Wirkung.', max_digits=4, verbose_name='Gewicht')),
            ],
            options={
                'verbose_name': 'Kriterium → Kompetenz',
                'verbose_name_plural': 'Kriterium → Kompetenz',
            },
        ),
        migrations.CreateModel(
            name='SelfAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('submitted', 'Eingereicht')], default='draft', max_length=20, verbose_name='Status')),
                ('overall_comment', models.TextField(blank=True, verbose_name='Gesamtkommentar')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eingereicht am')),
            ],
            options={
                'verbose_name': 'Selbstbeurteilung',
                'verbose_name_plural': 'Selbstbeurteilungen',
                'ordering': ['-assignment__end_date'],
            },
        ),
        migrations.CreateModel(
            name='SelfAssessmentRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20, verbose_name='Selbsteinschätzung')),
                ('comment', models.TextField(blank=True, verbose_name='Kommentar')),
            ],
            options={
                'verbose_name': 'Selbstbewertung (Kriterium)',
                'verbose_name_plural': 'Selbstbewertungen (Kriterien)',
            },
        ),
        migrations.CreateModel(
            name='StationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Eingereicht am')),
                ('comment', models.TextField(blank=True, help_text='Optionaler allgemeiner Kommentar (anonym).', verbose_name='Anmerkungen')),
            ],
            options={
                'verbose_name': 'Stationsbewertung',
                'verbose_name_plural': 'Stationsbewertungen',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='StationFeedbackCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Kurzbezeichnung für die interne Verwaltung.', max_length=80, unique=True, verbose_name='Interner Name')),
                ('label', models.CharField(help_text='Wird im Bewertungsformular angezeigt.', max_length=120, verbose_name='Bezeichnung')),
                ('help_text', models.TextField(blank=True, help_text='Optionaler Hinweistext für Nachwuchskräfte.', verbose_name='Erläuterung')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Stationsbewertungs-Kategorie',
                'verbose_name_plural': 'Stationsbewertungs-Kategorien',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StationFeedbackRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(help_text='Schulnote 1 (sehr gut) bis 6 (ungenügend).', verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Stationsbewertung (Kategorie)',
                'verbose_name_plural': 'Stationsbewertungen (Kategorien)',
            },
        ),
    ]
