# Generated by Django 6.0.3 on 2026-05-03 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment', '0002_initial'),
        ('course', '0001_initial'),
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='escalated_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_assessments', to='instructor.trainingcoordination', verbose_name='Eskaliert an'),
        ),
        migrations.AddField(
            model_name='assessmentcriterion',
            name='job_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_criteria', to='course.jobprofile', verbose_name='Berufsbild'),
        ),
        migrations.AddField(
            model_name='assessmentrating',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='assessment.assessment'),
        ),
        migrations.AddField(
            model_name='assessmentrating',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assessment.assessmentcriterion', verbose_name='Kriterium'),
        ),
        migrations.AddField(
            model_name='assessmenttemplate',
            name='job_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_templates', to='course.jobprofile', verbose_name='Berufsbild'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assessment.assessmenttemplate', verbose_name='Beurteilungsvorlage'),
        ),
        migrations.AddField(
            model_name='assessmenttemplatecriterion',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.assessmentcriterion'),
        ),
        migrations.AddField(
            model_name='assessmenttemplatecriterion',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.assessmenttemplate'),
        ),
        migrations.AddField(
            model_name='assessmenttemplate',
            name='criteria',
            field=models.ManyToManyField(blank=True, through='assessment.AssessmentTemplateCriterion', to='assessment.assessmentcriterion', verbose_name='Kriterien'),
        ),
    ]
