# Generated by Django 6.0.3 on 2026-05-03 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment', '0003_initial'),
        ('course', '0001_initial'),
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterioncompetenceweight',
            name='competence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_weights', to='organisation.competence', verbose_name='Kompetenz'),
        ),
        migrations.AddField(
            model_name='criterioncompetenceweight',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competence_weights', to='assessment.assessmentcriterion', verbose_name='Kriterium'),
        ),
        migrations.AddField(
            model_name='assessmentcriterion',
            name='competences',
            field=models.ManyToManyField(blank=True, help_text='Auf welche Kompetenzen zahlt dieses Kriterium ein? Grundlage für die Kompetenzmatrix.', related_name='assessment_criteria', through='assessment.CriterionCompetenceWeight', to='organisation.competence', verbose_name='Kompetenz-Mapping'),
        ),
        migrations.AddField(
            model_name='selfassessment',
            name='assignment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='self_assessment', to='course.internshipassignment', verbose_name='Praktikumseinsatz'),
        ),
        migrations.AddField(
            model_name='selfassessment',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assessment.assessmenttemplate', verbose_name='Beurteilungsvorlage'),
        ),
        migrations.AddField(
            model_name='selfassessmentrating',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assessment.assessmentcriterion', verbose_name='Kriterium'),
        ),
        migrations.AddField(
            model_name='selfassessmentrating',
            name='self_assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='assessment.selfassessment'),
        ),
        migrations.AddField(
            model_name='stationfeedback',
            name='schedule_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='station_feedbacks', to='course.scheduleblock', verbose_name='Praxisblock'),
        ),
        migrations.AddField(
            model_name='stationfeedback',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='station_feedbacks', to='organisation.organisationalunit', verbose_name='Organisationseinheit'),
        ),
        migrations.AddField(
            model_name='stationfeedbackrating',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assessment.stationfeedbackcategory', verbose_name='Kategorie'),
        ),
        migrations.AddField(
            model_name='stationfeedbackrating',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='assessment.stationfeedback'),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentrating',
            unique_together={('assessment', 'criterion')},
        ),
        migrations.AlterUniqueTogether(
            name='assessmenttemplatecriterion',
            unique_together={('template', 'criterion')},
        ),
        migrations.AlterUniqueTogether(
            name='criterioncompetenceweight',
            unique_together={('criterion', 'competence')},
        ),
        migrations.AlterUniqueTogether(
            name='selfassessmentrating',
            unique_together={('self_assessment', 'criterion')},
        ),
        migrations.AlterUniqueTogether(
            name='stationfeedbackrating',
            unique_together={('feedback', 'category')},
        ),
    ]
