# Generated by Django 6.0.3 on 2026-05-03 17:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('student', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyDayPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('internship_only', 'Nur während Praktika'), ('entire_course', 'Gesamter Ausbildungsverlauf')], default='entire_course', help_text='Legen Sie fest, in welchem Zeitraum Lern- und Studientage genommen werden dürfen.', max_length=20, verbose_name='Geltungsbereich')),
                ('allocation_type', models.CharField(choices=[('total', 'Gesamtbudget (fester Betrag)'), ('per_block', 'Tage je Block'), ('per_week', 'Tage je Woche'), ('per_month', 'Tage je Monat')], default='total', max_length=20, verbose_name='Zuteilungsart')),
                ('amount', models.PositiveSmallIntegerField(help_text='Anzahl der Tage entsprechend der gewählten Zuteilungsart. Bei Staffelung gilt dieser Wert für das 1. Ausbildungsjahr.', verbose_name='Anzahl Tage (Jahr 1)')),
                ('amount_year2', models.PositiveSmallIntegerField(blank=True, help_text='Überschreibt die Grundanzahl im 2. Ausbildungsjahr. Leer = wie Jahr 1.', null=True, verbose_name='Anzahl Tage (Jahr 2)')),
                ('amount_year3', models.PositiveSmallIntegerField(blank=True, help_text='Überschreibt die Grundanzahl ab dem 3. Ausbildungsjahr. Leer = wie Jahr 1.', null=True, verbose_name='Anzahl Tage (Jahr 3+)')),
                ('cap_per_month', models.PositiveSmallIntegerField(blank=True, help_text='Optionale monatliche Obergrenze, unabhängig von der Zuteilungsart. Leer = keine monatliche Begrenzung.', null=True, verbose_name='Max. Tage je Monat')),
                ('allow_carryover', models.BooleanField(default=False, help_text='Gibt an, ob nicht genutzte Tage in das nächste Ausbildungsjahr übertragen werden dürfen.', verbose_name='Übertragung ins Folgejahr erlaubt')),
                ('exam_prep_days', models.PositiveSmallIntegerField(blank=True, help_text='Separates jährliches Budget für Prüfungsvorbereitung, zusätzlich zu den regulären Lerntagen. Leer = kein separates Kontingent.', null=True, verbose_name='Prüfungsvorbereitungstage je Jahr')),
                ('min_advance_days', models.PositiveSmallIntegerField(default=0, help_text='Antrag muss mindestens diese Anzahl Tage im Voraus eingereicht werden. 0 = keine Frist.', verbose_name='Beantragungsfrist (Tage)')),
                ('max_days_per_request', models.PositiveSmallIntegerField(default=1, help_text='Maximale Anzahl aufeinanderfolgender Tage, die pro Antrag beantragt werden können. 1 = nur Einzeltage.', verbose_name='Max. Tage je Antrag')),
                ('allowed_weekdays', models.CharField(blank=True, help_text='Kommagetrennte Wochentage (0=Mo, 1=Di, …, 6=So). Leer = alle Tage erlaubt.', max_length=20, verbose_name='Erlaubte Wochentage')),
                ('notes', models.TextField(blank=True, help_text='Optionale interne Anmerkungen zu dieser Regelung.', verbose_name='Hinweise')),
                ('job_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_day_policy', to='course.jobprofile', verbose_name='Berufsbild')),
            ],
            options={
                'verbose_name': 'Lerntage-Regelung',
                'verbose_name_plural': 'Lerntage-Regelungen',
                'ordering': ['job_profile__job_profile'],
            },
        ),
        migrations.CreateModel(
            name='StudyDayBlackout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Beginn')),
                ('end_date', models.DateField(verbose_name='Ende')),
                ('label', models.CharField(blank=True, help_text='Z. B. „Prüfungszeitraum" oder „Betriebsferien".', max_length=200, verbose_name='Bezeichnung')),
                ('is_recurring_annually', models.BooleanField(default=False, help_text='Wenn aktiviert, gilt die Sperre jedes Jahr in demselben Zeitraum (nur Monat und Tag werden geprüft).', verbose_name='Jährlich wiederkehrend')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blackouts', to='studyday.studydaypolicy', verbose_name='Regelung')),
            ],
            options={
                'verbose_name': 'Sperrzeitraum',
                'verbose_name_plural': 'Sperrzeiträume',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='StudyDayRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Öffentliche ID')),
                ('date', models.DateField(verbose_name='Datum (von)')),
                ('date_end', models.DateField(blank=True, help_text='Leer = eintägiger Antrag.', null=True, verbose_name='Datum (bis)')),
                ('request_type', models.CharField(choices=[('study', 'Lerntag'), ('exam_prep', 'Prüfungsvorbereitung')], default='study', max_length=20, verbose_name='Art')),
                ('reason', models.TextField(blank=True, help_text='Optionale Begründung für den Lerntag.', verbose_name='Begründung')),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('approved', 'Genehmigt'), ('rejected', 'Abgelehnt'), ('cancelled', 'Storniert')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Beantragt am')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Freigegeben / Abgelehnt am')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Ablehnungsgrund')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Storniert am')),
                ('notification_sequence', models.PositiveIntegerField(default=0, help_text='Wird bei jedem Update inkrementiert; Outlook erkennt Termin-Updates über UID + SEQUENCE.', verbose_name='iCal-Sequenznummer')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_day_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Freigegeben / Abgelehnt von')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_day_cancellations', to=settings.AUTH_USER_MODEL, verbose_name='Storniert von')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_day_requests', to='student.student', verbose_name='Nachwuchskraft')),
            ],
            options={
                'verbose_name': 'Lerntag-Antrag',
                'verbose_name_plural': 'Lerntag-Anträge',
                'ordering': ['-date'],
            },
        ),
    ]
