# Generated by Django 6.0.3 on 2026-05-03 17:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Öffentliche ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Bezeichnung')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
            ],
            options={
                'verbose_name': 'Kompetenz',
                'verbose_name_plural': 'Kompetenzen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Öffentliche ID')),
                ('name', models.CharField(max_length=200, verbose_name='Bezeichnung')),
            ],
            options={
                'verbose_name': 'Standort',
                'verbose_name_plural': 'Standorte',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganisationalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Öffentliche ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('label', models.CharField(default='', max_length=200, verbose_name='Bezeichnung')),
                ('unit_type', models.CharField(choices=[('authority', 'Behörde'), ('department', 'Abteilung'), ('division_group', 'Referatsgruppe'), ('division', 'Referat'), ('section', 'Sachgebiet')], max_length=30, verbose_name='Art der Organisationseinheit')),
                ('max_capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Max. Kapazität')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'Organisationseinheit',
                'verbose_name_plural': 'Organisationseinheiten',
                'ordering': ['unit_type', 'name'],
            },
        ),
    ]
