# Generated by Django 6.0.3 on 2026-05-03 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisation', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='services.adress', verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='organisationalunit',
            name='competences',
            field=models.ManyToManyField(blank=True, related_name='units', to='organisation.competence', verbose_name='Kompetenzen'),
        ),
        migrations.AddField(
            model_name='organisationalunit',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='units', to='organisation.location', verbose_name='Standorte'),
        ),
        migrations.AddField(
            model_name='organisationalunit',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='organisation.organisationalunit', verbose_name='Übergeordnete Organisationseinheit'),
        ),
    ]
