# Generated by Django 6.0.3 on 2026-05-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='holiday_state',
            field=models.CharField(blank=True, choices=[('', 'Keine (nur bundesweite Feiertage)'), ('BB', 'Brandenburg'), ('BE', 'Berlin'), ('BW', 'Baden-Württemberg'), ('BY', 'Bayern'), ('HB', 'Bremen'), ('HE', 'Hessen'), ('HH', 'Hamburg'), ('MV', 'Mecklenburg-Vorpommern'), ('NI', 'Niedersachsen'), ('NW', 'Nordrhein-Westfalen'), ('RP', 'Rheinland-Pfalz'), ('SH', 'Schleswig-Holstein'), ('SL', 'Saarland'), ('SN', 'Sachsen'), ('ST', 'Sachsen-Anhalt'), ('TH', 'Thüringen')], default='', help_text='Bundesland des Standorts; bestimmt die gesetzlichen Feiertage bei der Arbeitstagsermittlung für Anwesende.', max_length=2, verbose_name='Bundesland (Feiertage)'),
        ),
    ]
