# Generated by Django 6.0.3 on 2026-05-03 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0003_location_holiday_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='holiday_state',
        ),
    ]
