# Generated by Django 6.0.3 on 2026-05-03 17:50

import course.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockLetterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Verfügbare Platzhalter: {{ block_name }}, {{ block_start }}, {{ block_end }}, {{ block_location }}, {{ freitext }}, {{ student_vorname }}, {{ student_nachname }}, {{ anrede }}, {{ kurs }}, {{ heute }}, {{ ersteller_vorname }}, {{ ersteller_nachname }}, {{ ersteller_funktion }}, {{ ersteller_standort }}, {{ ersteller_durchwahl }}', verbose_name='Beschreibung')),
                ('template_file', models.FileField(upload_to='course/zuweisungsschreiben_vorlagen/', verbose_name='Vorlage (.docx)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zuweisungsschreiben-Vorlage',
                'verbose_name_plural': 'Zuweisungsschreiben-Vorlagen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('abbreviation', models.CharField(max_length=2, primary_key=True, serialize=False, unique=True, verbose_name='Abkürzung')),
                ('description', models.CharField(max_length=100, verbose_name='Bezeichnung')),
            ],
            options={
                'verbose_name': 'Laufbahn',
                'verbose_name_plural': 'Laufbahnen',
            },
        ),
        migrations.CreateModel(
            name='CompetenceTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_value', models.DecimalField(decimal_places=2, default=80.0, help_text='Wert, der am Ende der Ausbildung erreicht sein soll.', max_digits=5, verbose_name='Endziel-Wert (0–100)')),
            ],
            options={
                'verbose_name': 'Kompetenz-Endziel',
                'verbose_name_plural': 'Kompetenz-Endziele',
                'ordering': ['job_profile', 'competence__name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Kursnummer')),
                ('start_date', models.DateField(verbose_name='Startdatum')),
                ('end_date', models.DateField(verbose_name='Enddatum')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurse',
            },
        ),
        migrations.CreateModel(
            name='CourseChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
            ],
            options={
                'verbose_name': 'Kurs-Checkliste',
                'verbose_name_plural': 'Kurs-Checklisten',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Aufgabe')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('completed', models.BooleanField(default=False, verbose_name='Erledigt')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Erledigt am')),
            ],
            options={
                'verbose_name': 'Kurs-Checklisten-Punkt',
                'verbose_name_plural': 'Kurs-Checklisten-Punkte',
                'ordering': ['checklist', 'order', 'text'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Bestätigt am')),
                ('notes', models.TextField(blank=True, verbose_name='Anmerkung')),
            ],
            options={
                'verbose_name': 'Ausbildungsplan-Bestätigung',
                'verbose_name_plural': 'Ausbildungsplan-Bestätigungen',
            },
        ),
        migrations.CreateModel(
            name='CurriculumRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Öffentliche ID')),
                ('name', models.CharField(help_text='z. B. „Sachgebiet Personal" oder „Abteilung Haushalt"', max_length=200, verbose_name='Bezeichnung')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung / Lernziel')),
                ('min_duration_weeks', models.PositiveIntegerField(default=1, verbose_name='Mindestdauer (Wochen)')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Pflicht')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
            ],
            options={
                'verbose_name': 'Ausbildungsplan-Anforderung',
                'verbose_name_plural': 'Ausbildungsplan-Anforderungen',
                'ordering': ['job_profile', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GradeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
            ],
            options={
                'verbose_name': 'Notenart',
                'verbose_name_plural': 'Notenarten',
                'ordering': ['job_profile', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InternshipAssignment',
            fields=[
                ('id', models.CharField(default=course.models.create_internship_assignment_id, editable=False, primary_key=True, serialize=False, unique=True)),
                ('start_date', models.DateField(verbose_name='Beginn')),
                ('end_date', models.DateField(verbose_name='Ende')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notizen')),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('approved', 'Angenommen'), ('rejected', 'Abgelehnt')], default='pending', max_length=20, verbose_name='Status')),
                ('rejection_reason', models.TextField(blank=True, default='', verbose_name='Ablehnungsgrund')),
                ('station_feedback_submitted', models.BooleanField(default=False, help_text='Wird gesetzt, wenn die Nachwuchskraft die anonyme Stationsbewertung eingereicht hat.', verbose_name='Stationsbewertung abgegeben')),
                ('notification_sequence', models.PositiveIntegerField(default=0, help_text='Wird bei jedem Update inkrementiert; Outlook erkennt Termin-Updates über UID + SEQUENCE.', verbose_name='iCal-Sequenznummer')),
            ],
            options={
                'verbose_name': 'Praktikumseinsatz',
                'verbose_name_plural': 'Praktikumseinsätze',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='InternshipPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paperless_id', models.IntegerField(blank=True, null=True, verbose_name='Paperless-ID')),
                ('email_sent', models.BooleanField(default=False, verbose_name='E-Mail gesendet')),
            ],
            options={
                'verbose_name': 'Praktikumsplan-Eintrag',
                'verbose_name_plural': 'Praktikumsplan-Einträge',
            },
        ),
        migrations.CreateModel(
            name='InternshipPlanLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_text', models.TextField(blank=True, verbose_name='Freitext')),
                ('status', models.CharField(choices=[('pending_approval', 'Freigabe ausstehend'), ('sent', 'Versendet')], default='pending_approval', max_length=20, verbose_name='Status')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Freigegeben am')),
            ],
            options={
                'verbose_name': 'Praktikumsplan',
                'verbose_name_plural': 'Praktikumspläne',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='InternshipPlanTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Verfügbare Platzhalter: {{ student_vorname }}, {{ student_nachname }}, {{ anrede }}, {{ kurs }}, {{ block_name }}, {{ block_start }}, {{ block_end }}, {{ freitext }}, {{ heute }}, {{ ersteller_name }}, {{ ersteller_funktion }}, {{ ersteller_standort }}, {{ ersteller_durchwahl }} | Liste: {% for e in einsaetze %} {{ e.einheit }}, {{ e.von }}, {{ e.bis }}, {{ e.standort }}, {{ e.praxistutor }} {% endfor %}', verbose_name='Beschreibung')),
                ('template_file', models.FileField(upload_to='course/praktikumsplan_vorlagen/', verbose_name='Vorlage (.docx)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Praktikumsplan-Vorlage',
                'verbose_name_plural': 'Praktikumsplan-Vorlagen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_profile', models.CharField(max_length=120, verbose_name='Berufsbild')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('degree', models.CharField(max_length=120, verbose_name='Abschluss')),
                ('legal_basis', models.CharField(max_length=120, verbose_name='Gesetzesgrundlage')),
                ('requires_proof_of_training', models.BooleanField(default=False, help_text='Nachwuchskräfte mit diesem Berufsbild müssen wöchentliche Ausbildungsnachweise führen.', verbose_name='Ausbildungsnachweis erforderlich')),
            ],
            options={
                'verbose_name': 'Berufsbild',
                'verbose_name_plural': 'Berufsbilder',
            },
        ),
        migrations.CreateModel(
            name='ScheduleBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Öffentliche ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('start_date', models.DateField(verbose_name='Beginn')),
                ('end_date', models.DateField(verbose_name='Ende')),
                ('is_internship', models.BooleanField(default=False, verbose_name='Ist Praktikum')),
            ],
            options={
                'verbose_name': 'Ablaufblock',
                'verbose_name_plural': 'Ablaufblöcke',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('specialization', models.CharField(max_length=2, primary_key=True, serialize=False, unique=True, verbose_name='Abkürzung')),
                ('description', models.CharField(max_length=100, verbose_name='Beschreibung')),
            ],
            options={
                'verbose_name': 'Fachrichtung',
                'verbose_name_plural': 'Fachrichtungen',
            },
        ),
        migrations.CreateModel(
            name='StationLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_text', models.TextField(blank=True, verbose_name='Freitext')),
                ('status', models.CharField(choices=[('pending_approval', 'Freigabe ausstehend'), ('sent', 'Versendet')], default='pending_approval', max_length=20, verbose_name='Status')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Freigegeben am')),
            ],
            options={
                'verbose_name': 'Stationszuweisungsschreiben',
                'verbose_name_plural': 'Stationszuweisungsschreiben',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='StationLetterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paperless_id', models.IntegerField(blank=True, null=True, verbose_name='Paperless-ID')),
                ('email_sent', models.BooleanField(default=False, verbose_name='E-Mail gesendet')),
            ],
            options={
                'verbose_name': 'Stationsschreiben-Eintrag',
                'verbose_name_plural': 'Stationsschreiben-Einträge',
            },
        ),
        migrations.CreateModel(
            name='StationLetterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Verfügbare Platzhalter: {{ student_vorname }}, {{ student_nachname }}, {{ anrede }}, {{ kurs }}, {{ block_name }}, {{ block_start }}, {{ block_end }}, {{ freitext }}, {{ heute }}, {{ einheit }}, {{ einheit_beschreibung }}, {{ einsatz_von }}, {{ einsatz_bis }}, {{ standort }}, {{ praxistutor }}, {{ ersteller_name }}, {{ ersteller_funktion }}, {{ ersteller_standort }}, {{ ersteller_durchwahl }}', verbose_name='Beschreibung')),
                ('template_file', models.FileField(upload_to='course/stationsschreiben_vorlagen/', verbose_name='Vorlage (.docx)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stationsschreiben-Vorlage',
                'verbose_name_plural': 'Stationsschreiben-Vorlagen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Öffentliche ID')),
                ('change_type', models.CharField(choices=[('split', 'Einsatz teilen'), ('shift', 'Zeitraum verschieben'), ('unit_change', 'Stationswechsel'), ('instructor', 'Praxistutor wechseln'), ('location', 'Standortwechsel'), ('cancel', 'Einsatz stornieren')], max_length=20, verbose_name='Änderungstyp')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Typabhängige Felder, z. B. {"split_date": "2026-06-01"}.', verbose_name='Daten')),
                ('reason', models.TextField(blank=True, verbose_name='Begründung')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Beantragt am')),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('approved', 'Angenommen'), ('rejected', 'Abgelehnt')], default='pending', max_length=20, verbose_name='Status')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Entschieden am')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Ablehnungsgrund')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_requests_decided', to=settings.AUTH_USER_MODEL, verbose_name='Entschieden von')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_requests_made', to=settings.AUTH_USER_MODEL, verbose_name='Beantragt von')),
            ],
            options={
                'verbose_name': 'Änderungsantrag',
                'verbose_name_plural': 'Änderungsanträge',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_text', models.TextField(blank=True, verbose_name='Freitext')),
                ('status', models.CharField(choices=[('pending_approval', 'Freigabe ausstehend'), ('sent', 'Versendet')], default='pending_approval', max_length=20, verbose_name='Status')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Freigegeben am')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_block_letters', to=settings.AUTH_USER_MODEL, verbose_name='Freigegeben von')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_block_letters', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Zuweisungsschreiben',
                'verbose_name_plural': 'Zuweisungsschreiben',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockLetterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paperless_id', models.IntegerField(blank=True, null=True, verbose_name='Paperless-ID')),
                ('email_sent', models.BooleanField(default=False, verbose_name='E-Mail gesendet')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='course.blockletter', verbose_name='Zuweisungsschreiben')),
            ],
            options={
                'verbose_name': 'Zuweisungsschreiben-Eintrag',
                'verbose_name_plural': 'Zuweisungsschreiben-Einträge',
            },
        ),
    ]
