# Generated by Django 6.0.3 on 2026-05-03 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('instructor', '0001_initial'),
        ('organisation', '0001_initial'),
        ('student', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blockletteritem',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student', verbose_name='Nachwuchskraft'),
        ),
        migrations.AddField(
            model_name='competencetarget',
            name='competence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='organisation.competence', verbose_name='Kompetenz'),
        ),
        migrations.AddField(
            model_name='coursechecklist',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='course.course', verbose_name='Kurs'),
        ),
        migrations.AddField(
            model_name='coursechecklist',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von'),
        ),
        migrations.AddField(
            model_name='coursechecklist',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.checklisttemplate', verbose_name='Vorlage'),
        ),
        migrations.AddField(
            model_name='coursechecklistitem',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='course.coursechecklist', verbose_name='Checkliste'),
        ),
        migrations.AddField(
            model_name='coursechecklistitem',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_course_checklist_items', to=settings.AUTH_USER_MODEL, verbose_name='Erledigt von'),
        ),
        migrations.AddField(
            model_name='curriculumcompletion',
            name='completed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Bestätigt von'),
        ),
        migrations.AddField(
            model_name='curriculumcompletion',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_completions', to='student.student', verbose_name='Nachwuchskraft'),
        ),
        migrations.AddField(
            model_name='curriculumrequirement',
            name='target_competence',
            field=models.ForeignKey(blank=True, help_text='Wenn gesetzt, erfüllt jede OE mit dieser Kompetenz die Anforderung.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curriculum_requirements', to='organisation.competence', verbose_name='Ziel-Kompetenz'),
        ),
        migrations.AddField(
            model_name='curriculumrequirement',
            name='target_units',
            field=models.ManyToManyField(blank=True, help_text='Wenn gesetzt, erfüllt nur eine dieser OE die Anforderung (hat Vorrang vor Kompetenz).', related_name='curriculum_requirements', to='organisation.organisationalunit', verbose_name='Ziel-Organisationseinheiten'),
        ),
        migrations.AddField(
            model_name='curriculumcompletion',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='course.curriculumrequirement', verbose_name='Anforderung'),
        ),
        migrations.AddField(
            model_name='internshipassignment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Angelegt von'),
        ),
        migrations.AddField(
            model_name='internshipassignment',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instructor.instructor', verbose_name='Praxistutor'),
        ),
        migrations.AddField(
            model_name='internshipassignment',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internship_assignments', to='organisation.location', verbose_name='Standort'),
        ),
        migrations.AddField(
            model_name='internshipassignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship_assignments', to='student.student', verbose_name='Nachwuchskraft'),
        ),
        migrations.AddField(
            model_name='internshipassignment',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organisation.organisationalunit', verbose_name='Organisationseinheit'),
        ),
        migrations.AddField(
            model_name='assignmentchangerequest',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='course.internshipassignment', verbose_name='Praktikumseinsatz'),
        ),
        migrations.AddField(
            model_name='internshipplanitem',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student', verbose_name='Nachwuchskraft'),
        ),
        migrations.AddField(
            model_name='internshipplanletter',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_plan_letters', to=settings.AUTH_USER_MODEL, verbose_name='Freigegeben von'),
        ),
        migrations.AddField(
            model_name='internshipplanletter',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_plan_letters', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von'),
        ),
        migrations.AddField(
            model_name='internshipplanitem',
            name='letter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='course.internshipplanletter', verbose_name='Praktikumsplan'),
        ),
        migrations.AddField(
            model_name='jobprofile',
            name='career',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.career', verbose_name='Laufbahn'),
        ),
        migrations.AddField(
            model_name='internshipplantemplate',
            name='job_profile',
            field=models.ForeignKey(blank=True, help_text='Wenn gesetzt, gilt diese Vorlage nur für Kurse dieses Berufsbilds. Wenn leer, dient sie als Fallback für alle Berufsbilder.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internship_plan_templates', to='course.jobprofile', verbose_name='Berufsbild'),
        ),
        migrations.AddField(
            model_name='gradetype',
            name='job_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_types', to='course.jobprofile', verbose_name='Berufsbild'),
        ),
        migrations.AddField(
            model_name='curriculumrequirement',
            name='job_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_requirements', to='course.jobprofile', verbose_name='Berufsbild'),
        ),
        migrations.AddField(
            model_name='course',
            name='job_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.jobprofile', verbose_name='Berufsbild'),
        ),
        migrations.AddField(
            model_name='competencetarget',
            name='job_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competence_targets', to='course.jobprofile', verbose_name='Berufsbild'),
        ),
        migrations.AddField(
            model_name='blocklettertemplate',
            name='job_profile',
            field=models.ForeignKey(blank=True, help_text='Wenn gesetzt, gilt diese Vorlage nur für Kurse dieses Berufsbilds. Wenn leer, dient sie als Fallback für alle Berufsbilder.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block_letter_templates', to='course.jobprofile', verbose_name='Berufsbild'),
        ),
        migrations.AddField(
            model_name='scheduleblock',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_blocks', to='course.course', verbose_name='Kurs'),
        ),
        migrations.AddField(
            model_name='scheduleblock',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_blocks', to='organisation.location', verbose_name='Standort'),
        ),
        migrations.AddField(
            model_name='internshipplanletter',
            name='schedule_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_letters', to='course.scheduleblock', verbose_name='Ablaufblock'),
        ),
        migrations.AddField(
            model_name='internshipassignment',
            name='schedule_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship_assignments', to='course.scheduleblock', verbose_name='Praktikumsblock'),
        ),
        migrations.AddField(
            model_name='blockletter',
            name='schedule_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='course.scheduleblock', verbose_name='Ablaufblock'),
        ),
        migrations.AddField(
            model_name='jobprofile',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.specialization', verbose_name='Fachrichtung'),
        ),
        migrations.AddField(
            model_name='stationletter',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_station_letters', to=settings.AUTH_USER_MODEL, verbose_name='Freigegeben von'),
        ),
        migrations.AddField(
            model_name='stationletter',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_station_letters', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von'),
        ),
        migrations.AddField(
            model_name='stationletter',
            name='schedule_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_letters', to='course.scheduleblock', verbose_name='Ablaufblock'),
        ),
        migrations.AddField(
            model_name='stationletteritem',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.internshipassignment', verbose_name='Einsatz'),
        ),
        migrations.AddField(
            model_name='stationletteritem',
            name='letter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='course.stationletter', verbose_name='Stationsschreiben'),
        ),
        migrations.AddField(
            model_name='stationlettertemplate',
            name='job_profile',
            field=models.ForeignKey(blank=True, help_text='Wenn gesetzt, gilt diese Vorlage nur für Kurse dieses Berufsbilds. Wenn leer, dient sie als Fallback für alle Berufsbilder.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='station_letter_templates', to='course.jobprofile', verbose_name='Berufsbild'),
        ),
        migrations.AlterUniqueTogether(
            name='blockletteritem',
            unique_together={('letter', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='curriculumcompletion',
            unique_together={('requirement', 'student')},
        ),
        migrations.AddConstraint(
            model_name='assignmentchangerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('assignment', 'change_type'), name='unique_pending_change_request_per_type'),
        ),
        migrations.AlterUniqueTogether(
            name='internshipplanitem',
            unique_together={('letter', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='competencetarget',
            unique_together={('job_profile', 'competence')},
        ),
        migrations.AlterUniqueTogether(
            name='stationletteritem',
            unique_together={('letter', 'assignment')},
        ),
    ]
