# Generated by Django 6.0.3 on 2026-05-07 16:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def migrate_is_internship_forward(apps, schema_editor):
    ScheduleBlock = apps.get_model('course', 'ScheduleBlock')
    ScheduleBlock.objects.filter(is_internship=True).update(block_type='internship')
    ScheduleBlock.objects.filter(is_internship=False).update(block_type='normal')


def migrate_is_internship_backward(apps, schema_editor):
    ScheduleBlock = apps.get_model('course', 'ScheduleBlock')
    ScheduleBlock.objects.filter(block_type='internship').update(is_internship=True)
    ScheduleBlock.objects.exclude(block_type='internship').update(is_internship=False)


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleblock',
            name='block_type',
            field=models.CharField(choices=[('normal', 'Theoriephase'), ('internship', 'Praktikum'), ('seminar', 'Seminar')], default='normal', max_length=20, verbose_name='Blocktyp'),
        ),
        migrations.RunPython(migrate_is_internship_forward, migrate_is_internship_backward),
        migrations.RemoveField(
            model_name='scheduleblock',
            name='is_internship',
        ),
        migrations.CreateModel(
            name='SeminarLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Öffentliche ID')),
                ('topic', models.CharField(max_length=200, verbose_name='Thema')),
                ('description', models.TextField(blank=True, verbose_name='Inhalt')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Ort')),
                ('start_datetime', models.DateTimeField(verbose_name='Beginn')),
                ('end_datetime', models.DateTimeField(verbose_name='Ende')),
                ('speaker_name', models.CharField(max_length=150, verbose_name='Vortragender')),
                ('speaker_email', models.EmailField(max_length=254, verbose_name='E-Mail Vortragender')),
                ('status', models.CharField(choices=[('pending', 'Bestätigung ausstehend'), ('confirmed', 'Bestätigt'), ('declined', 'Abgelehnt')], default='pending', max_length=20, verbose_name='Status')),
                ('confirmation_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Bestätigungs-Token')),
                ('decline_reason', models.TextField(blank=True, verbose_name='Ablehnungsgrund')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Anfrage gesendet')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Antwort erhalten')),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Erinnerung gesendet')),
                ('notification_sequence', models.PositiveIntegerField(default=0, verbose_name='iCal-Sequenz')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lectures', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('schedule_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='course.scheduleblock', verbose_name='Seminarblock')),
            ],
            options={
                'verbose_name': 'Vortrag',
                'verbose_name_plural': 'Vorträge',
                'ordering': ['start_datetime'],
            },
        ),
    ]