# Generated by Django 6.0.3 on 2026-05-03 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Zeitpunkt')),
                ('action', models.CharField(choices=[('create', 'Erstellt'), ('update', 'Geändert'), ('delete', 'Gelöscht'), ('submit', 'Eingereicht'), ('login', 'Anmeldung'), ('logout', 'Abmeldung'), ('login_failed', 'Anmeldung fehlgeschlagen'), ('backup', 'Backup erstellt'), ('backup_failed', 'Backup fehlgeschlagen'), ('restore', 'Wiederherstellung')], max_length=20, verbose_name='Aktion')),
                ('app_label', models.CharField(max_length=100)),
                ('model_name', models.CharField(db_index=True, max_length=100)),
                ('model_verbose_name', models.CharField(max_length=200, verbose_name='Objekt-Typ')),
                ('object_id', models.CharField(db_index=True, max_length=200, verbose_name='Objekt-ID')),
                ('object_repr', models.TextField(verbose_name='Objekt')),
                ('changes', models.JSONField(default=dict, verbose_name='Änderungen')),
                ('student_id', models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Nachwuchskraft-ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_log_entries', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Änderungsprotokoll-Eintrag',
                'verbose_name_plural': 'Änderungsprotokoll',
                'ordering': ['-timestamp'],
            },
        ),
    ]
