# Generated by Django 6.0.3 on 2026-05-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogentry',
            name='action',
            field=models.CharField(choices=[('create', 'Erstellt'), ('update', 'Geändert'), ('delete', 'Gelöscht'), ('submit', 'Eingereicht'), ('login', 'Anmeldung'), ('logout', 'Abmeldung'), ('login_failed', 'Anmeldung fehlgeschlagen'), ('backup', 'Backup erstellt'), ('backup_failed', 'Backup fehlgeschlagen'), ('restore', 'Wiederherstellung'), ('unlock', 'Konto entsperrt')], max_length=20, verbose_name='Aktion'),
        ),
    ]
