# Generated by Django 6.0.3 on 2026-05-03 17:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacation_office_email', models.EmailField(blank=True, db_column='urlaubsstelle_email', help_text='Täglich werden Urlaubsanträge und Krankmeldungen an diese Adresse gesendet.', max_length=254, verbose_name='E-Mail Urlaubsstelle')),
                ('holiday_state', models.CharField(blank=True, choices=[('', 'Keine (nur bundesweite Feiertage)'), ('BB', 'Brandenburg'), ('BE', 'Berlin'), ('BW', 'Baden-Württemberg'), ('BY', 'Bayern'), ('HB', 'Bremen'), ('HE', 'Hessen'), ('HH', 'Hamburg'), ('MV', 'Mecklenburg-Vorpommern'), ('NI', 'Niedersachsen'), ('NW', 'Nordrhein-Westfalen'), ('RP', 'Rheinland-Pfalz'), ('SH', 'Schleswig-Holstein'), ('SL', 'Saarland'), ('SN', 'Sachsen'), ('ST', 'Sachsen-Anhalt'), ('TH', 'Thüringen')], default='', help_text='Bundesland für die Berechnung gesetzlicher Feiertage bei der Arbeitstagsermittlung.', max_length=2, verbose_name='Bundesland (Feiertage)')),
            ],
            options={
                'verbose_name': 'Abwesenheitseinstellungen',
                'verbose_name_plural': 'Abwesenheitseinstellungen',
            },
        ),
        migrations.CreateModel(
            name='StudentAbsenceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traffic_light', models.CharField(choices=[('green', 'Grün (< 5 %)'), ('yellow', 'Gelb (≥ 5 %)'), ('red', 'Rot (≥ 10 %)'), ('unknown', 'Unbekannt')], default='unknown', max_length=10, verbose_name='Ampel')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Abwesenheitsstatus',
                'verbose_name_plural': 'Abwesenheitsstatus',
            },
        ),
        migrations.CreateModel(
            name='VacationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Versendet am')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Bearbeitet am')),
                ('processed_by_name', models.CharField(blank=True, max_length=200, verbose_name='Bearbeitet von')),
            ],
            options={
                'verbose_name': 'Urlaubsantragspaket',
                'verbose_name_plural': 'Urlaubsantragspakete',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='VacationConfirmationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Verfügbare Platzhalter je Antrag (in {% for antrag in antraege %}-Schleife): {{ antrag.vorname }}, {{ antrag.nachname }}, {{ antrag.von }}, {{ antrag.bis }}, {{ antrag.arbeitstage }}, {{ antrag.resturlaub_aktuell }}, {{ antrag.resturlaub_vorjahr }}, {{ antrag.antragsart }}, {{ antrag.kurs }} | Global: {{ heute }}, {{ bearbeitet_von }}', verbose_name='Beschreibung')),
                ('template_file', models.FileField(upload_to='absence/vorlagen/', verbose_name='Vorlage (.docx)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Urlaubsbestätigungs-Vorlage',
                'verbose_name_plural': 'Urlaubsbestätigungs-Vorlagen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VacationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Öffentliche ID')),
                ('start_date', models.DateField(verbose_name='Von')),
                ('end_date', models.DateField(verbose_name='Bis')),
                ('notes', models.TextField(blank=True, verbose_name='Anmerkungen')),
                ('is_cancellation', models.BooleanField(default=False, verbose_name='Stornierungsantrag')),
                ('submitted_via_portal', models.BooleanField(default=False, verbose_name='Im Portal eingereicht')),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('approved', 'Genehmigt'), ('rejected', 'Abgelehnt'), ('processed', 'Durch Urlaubsstelle bearbeitet'), ('cancelled', 'Storniert')], default='pending', max_length=20, verbose_name='Status')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Freigegeben/Abgelehnt am')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Ablehnungsgrund')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Storniert am')),
                ('remaining_days_current_year', models.SmallIntegerField(blank=True, null=True, verbose_name='Resturlaub aktuelles Jahr')),
                ('remaining_days_previous_year', models.SmallIntegerField(blank=True, null=True, verbose_name='Resturlaub Vorjahr')),
                ('manual_working_days', models.SmallIntegerField(blank=True, help_text='Wenn gesetzt, überschreibt diese Zahl die automatisch berechneten Arbeitstage (z. B. wegen interner Regelungen).', null=True, verbose_name='Arbeitstage (manuell)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Urlaubsantrag',
                'verbose_name_plural': 'Urlaubsanträge',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SickLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Öffentliche ID')),
                ('start_date', models.DateField(verbose_name='Erster Krankheitstag')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Letzter Krankheitstag')),
                ('sick_type', models.CharField(choices=[('selbstauskunft', 'Selbstauskunft'), ('k_taste', 'K-Taste'), ('attest', 'Attest')], default='selbstauskunft', max_length=20, verbose_name='Art')),
                ('notes', models.TextField(blank=True, verbose_name='Anmerkungen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Gesundgemeldet am')),
                ('opening_reported', models.BooleanField(default=False, verbose_name='Öffnung gemeldet')),
                ('closing_reported', models.BooleanField(default=False, verbose_name='Schließung gemeldet')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sick_leaves_closed', to=settings.AUTH_USER_MODEL, verbose_name='Gesundgemeldet von')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sick_leaves_created', to=settings.AUTH_USER_MODEL, verbose_name='Erfasst von')),
            ],
            options={
                'verbose_name': 'Krankmeldung',
                'verbose_name_plural': 'Krankmeldungen',
                'ordering': ['-start_date'],
            },
        ),
    ]
