# Generated by Django 6.0.3 on 2026-05-03 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('absence', '0001_initial'),
        ('student', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sickleave',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sick_leaves', to='student.student', verbose_name='Nachwuchskraft'),
        ),
        migrations.AddField(
            model_name='studentabsencestate',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='absence_state', to='student.student', verbose_name='Nachwuchskraft'),
        ),
        migrations.AddField(
            model_name='vacationrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacation_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Freigegeben/Abgelehnt von'),
        ),
        migrations.AddField(
            model_name='vacationrequest',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='absence.vacationbatch', verbose_name='Paket'),
        ),
        migrations.AddField(
            model_name='vacationrequest',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacation_cancellations', to=settings.AUTH_USER_MODEL, verbose_name='Storniert von'),
        ),
        migrations.AddField(
            model_name='vacationrequest',
            name='original_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancellation_requests', to='absence.vacationrequest', verbose_name='Ursprünglicher Antrag'),
        ),
        migrations.AddField(
            model_name='vacationrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_requests', to='student.student', verbose_name='Nachwuchskraft'),
        ),
    ]
