# Generated by Django 6.0.3 on 2026-05-03 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0002_initial'),
        ('organisation', '0003_location_holiday_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationrequest',
            name='location_override',
            field=models.ForeignKey(blank=True, help_text='Wenn gesetzt, überschreibt dieser Standort den automatisch ermittelten Standort für die Feiertagsberechnung. Nur durch Ausbildungsreferat/Ausbildungsleitung änderbar.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacation_request_overrides', to='organisation.location', verbose_name='Standort (manuell)'),
        ),
    ]
