# Generated by Django 6.0.3 on 2026-05-03 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('organisation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200, verbose_name='Straße')),
                ('house_number', models.CharField(max_length=20, verbose_name='Hausnummer')),
                ('zip_code', models.CharField(max_length=10, verbose_name='PLZ')),
                ('city', models.CharField(max_length=100, verbose_name='Ort')),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adressen',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('abbreviation', models.CharField(max_length=1, primary_key=True, serialize=False, unique=True, verbose_name='Abkürzung')),
                ('gender', models.CharField(default='', max_length=100, verbose_name='Geschlecht')),
                ('description', models.CharField(default='', max_length=100, verbose_name='Beschreibung/Anrede')),
            ],
            options={
                'verbose_name': 'Geschlecht',
                'verbose_name_plural': 'Geschlechter',
                'db_table': 'student_gender',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('instructor_assignment', 'Praxistutor: Nachwuchskraft zugewiesen'), ('instructor_confirmed', 'Bestellungsschreiben: Praxistutor bestätigt'), ('instructor_confirmed_coordinator', 'Praxistutor bestätigt: Information an Koordination'), ('chief_assignment', 'Ausbildungskoordination: Einsatz angelegt/geändert'), ('chief_welcome', 'Willkommen: Benutzerkonto angelegt'), ('reminder_start', 'Erinnerung: Einsatz beginnt in 7 Tagen'), ('reminder_end', 'Erinnerung: Einsatz endet in 7 Tagen'), ('assignment_approved', 'Rückmeldung: Einsatz angenommen'), ('assignment_rejected', 'Rückmeldung: Einsatz abgelehnt'), ('practice_grade_confirmed', 'Bewertung: Praxisabschnitt bestätigt'), ('proof_of_training_approved', 'Ausbildungsnachweis: Angenommen'), ('proof_of_training_rejected', 'Ausbildungsnachweis: Korrekturbedarf'), ('proof_of_training_reminder', 'Erinnerung: Ausbildungsnachweis fehlt oder nicht eingereicht'), ('student_portal_welcome', 'Portal-Begrüßung: Zugangsdaten Nachwuchskraft'), ('study_day_approved', 'Lerntag: Antrag genehmigt'), ('study_day_rejected', 'Lerntag: Antrag abgelehnt'), ('study_day_cancelled', 'Lerntag: Genehmigter Tag storniert'), ('vacation_approved', 'Urlaub: Antrag genehmigt'), ('vacation_rejected', 'Urlaub: Antrag abgelehnt'), ('vacation_processed', 'Urlaub: Durch Urlaubsstelle bearbeitet'), ('inventory_issued', 'Inventar: Gegenstand ausgegeben'), ('inventory_returned', 'Inventar: Gegenstand zurückgegeben'), ('assessment_token_sent', 'Beurteilung: Link an Praxistutoren gesendet'), ('assessment_reminder', 'Beurteilung: Erinnerung an Praxistutoren (Stufe 1)'), ('assessment_reminder_urgent', 'Beurteilung: Dringende Erinnerung an Praxistutoren (Stufe 2)'), ('assessment_escalation', 'Beurteilung: Eskalation an Ausbildungskoordination (Stufe 3)'), ('assessment_submitted', 'Beurteilung: Praxistutoren hat eingereicht'), ('inquiry_new', 'Nachricht: Neue Anfrage von Nachwuchskraft'), ('inquiry_reply', 'Nachricht: Antwort vom Ausbildungsreferat'), ('document_generated', 'Dokument: Bescheinigung erstellt'), ('change_request_submitted', 'Änderungsantrag: Neuer Antrag eingegangen'), ('change_request_approved', 'Änderungsantrag: Antrag genehmigt'), ('change_request_rejected', 'Änderungsantrag: Antrag abgelehnt'), ('assignment_decision_for_office', 'Praktikumseinsatz: Entscheidung der Koordination (Info Referat)')], max_length=50, unique=True, verbose_name='Typ')),
                ('subject', models.CharField(max_length=250, verbose_name='Betreff')),
                ('body', models.TextField(verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Benachrichtigungsvorlage',
                'verbose_name_plural': 'Benachrichtigungsvorlagen',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impressum_text', models.TextField(blank=True, verbose_name='Impressum-Text')),
                ('datenschutz_text', models.TextField(blank=True, verbose_name='Datenschutz-Text')),
                ('brand_name', models.CharField(default='azubi.', help_text='Wird in der Navigationsleiste und im Browser-Tab angezeigt.', max_length=50, verbose_name='App-Name')),
                ('brand_header', models.CharField(default='Eine offizielle Anwendung der Abteilung X in der Bundesbehörde Z', help_text='Wird in der Kopfzeile über der Navigationsleiste angezeigt.', max_length=175, verbose_name='Kopfzeile')),
                ('brand_primary_color', models.CharField(default='#0d6efd', max_length=7, verbose_name='Primärfarbe')),
                ('brand_secondary_color', models.CharField(default='#6c757d', max_length=7, verbose_name='Sekundärfarbe')),
                ('brand_success_color', models.CharField(default='#198754', max_length=7, verbose_name='Erfolg')),
                ('brand_danger_color', models.CharField(default='#dc3545', max_length=7, verbose_name='Gefahr')),
                ('brand_warning_color', models.CharField(default='#ffc107', max_length=7, verbose_name='Warnung')),
                ('brand_info_color', models.CharField(default='#0dcaf0', max_length=7, verbose_name='Info')),
                ('reminder_days_before_start', models.PositiveSmallIntegerField(default=7, help_text='Wie viele Tage vor Beginn eines Praxiseinsatzes der Praxistutor erinnert wird.', verbose_name='Vorlauf Einsatzbeginn (Tage)')),
                ('reminder_days_before_end', models.PositiveSmallIntegerField(default=7, help_text='Wie viele Tage vor Ende eines Praxiseinsatzes der Praxistutor erinnert wird.', verbose_name='Vorlauf Einsatzende (Tage)')),
                ('reminder_hour', models.PositiveSmallIntegerField(default=7, help_text='Stunde (0–23), zu der die Praxiseinsatz-Erinnerungen und Ausbildungsnachweis-Erinnerungen versendet werden.', verbose_name='Uhrzeit Erinnerungen (Stunde)')),
                ('reminder_minute', models.PositiveSmallIntegerField(default=0, help_text='Minute (0–59).', verbose_name='Uhrzeit Erinnerungen (Minute)')),
                ('escalation_stage1_days', models.PositiveSmallIntegerField(default=3, help_text='Tage nach Token-Versand, bis die erste Erinnerung an den Praxistutor geht.', verbose_name='Eskalation Stufe 1: Erste Erinnerung (Tage)')),
                ('escalation_stage2_days', models.PositiveSmallIntegerField(default=7, help_text='Tage nach erster Erinnerung, bis die zweite (schärfere) Erinnerung gesendet wird.', verbose_name='Eskalation Stufe 2: Zweite Erinnerung (Tage)')),
                ('escalation_final_days', models.PositiveSmallIntegerField(default=14, help_text='Tage nach Token-Versand, bis die zuständige Ausbildungskoordination informiert wird.', verbose_name='Eskalation Stufe 3: Information an Koordination (Tage)')),
                ('anonymization_months', models.PositiveSmallIntegerField(default=12, help_text='Nach wie vielen Monaten Inaktivität (Statuswechsel) eine Nachwuchskraft anonymisiert wird.', verbose_name='Anonymisierungsfrist (Monate)')),
                ('anonymization_hour', models.PositiveSmallIntegerField(default=12, help_text='Stunde (0–23), zu der die nächtliche Anonymisierung läuft.', verbose_name='Uhrzeit Anonymisierung (Stunde)')),
                ('anonymization_minute', models.PositiveSmallIntegerField(default=0, help_text='Minute (0–59).', verbose_name='Uhrzeit Anonymisierung (Minute)')),
                ('vacation_batch_hour', models.PositiveSmallIntegerField(default=8, help_text='Stunde (0–23), zu der genehmigte Urlaubsanträge gebündelt an die Urlaubsstelle gesendet werden.', verbose_name='Uhrzeit Urlaubsantragspaket (Stunde)')),
                ('vacation_batch_minute', models.PositiveSmallIntegerField(default=0, help_text='Minute (0–59).', verbose_name='Uhrzeit Urlaubsantragspaket (Minute)')),
                ('sick_leave_report_hour', models.PositiveSmallIntegerField(default=8, help_text='Stunde (0–23), zu der der tägliche Bericht über Krank- und Gesundmeldungen versendet wird.', verbose_name='Uhrzeit Krankmeldungsbericht (Stunde)')),
                ('sick_leave_report_minute', models.PositiveSmallIntegerField(default=5, help_text='Minute (0–59).', verbose_name='Uhrzeit Krankmeldungsbericht (Minute)')),
                ('assessment_escalation_hour', models.PositiveSmallIntegerField(default=7, help_text='Stunde (0–23), zu der täglich der Eskalationslauf für ausstehende Stationsbeurteilungen läuft.', verbose_name='Uhrzeit Eskalationslauf (Stunde)')),
                ('assessment_escalation_minute', models.PositiveSmallIntegerField(default=30, help_text='Minute (0–59).', verbose_name='Uhrzeit Eskalationslauf (Minute)')),
                ('paperless_cache_interval_seconds', models.PositiveIntegerField(default=120, help_text='Wie oft (in Sekunden) der Paperless-Eingangskorb-Cache aktualisiert wird.', verbose_name='Paperless-Cache-Intervall (Sekunden)')),
                ('backup_hour', models.PositiveSmallIntegerField(default=2, help_text='Stunde (0–23), zu der das tägliche Backup von Datenbank, Media und Paperless läuft.', verbose_name='Uhrzeit Backup (Stunde)')),
                ('backup_minute', models.PositiveSmallIntegerField(default=0, help_text='Minute (0–59).', verbose_name='Uhrzeit Backup (Minute)')),
                ('backup_offsite_hour', models.PositiveSmallIntegerField(default=3, help_text='Stunde, zu der lokale Backups via restic auf das NAS gespiegelt werden.', verbose_name='Uhrzeit Off-Site-Sync (Stunde)')),
                ('backup_offsite_minute', models.PositiveSmallIntegerField(default=0, help_text='Minute (0–59).', verbose_name='Uhrzeit Off-Site-Sync (Minute)')),
                ('backup_keep_weekly', models.PositiveSmallIntegerField(default=4, help_text='Anzahl wöchentlicher Backups, die zusätzlich zu den täglichen vorgehalten werden.', verbose_name='Wöchentliche Backups vorhalten')),
                ('backup_keep_monthly', models.PositiveSmallIntegerField(default=12, help_text='Anzahl monatlicher Backups (Jahres-Historie).', verbose_name='Monatliche Backups vorhalten')),
                ('paperless_url', models.URLField(blank=True, default='', help_text='Basis-URL der Paperless-ngx-Instanz, z.\u202fB. http://paperless:8000', verbose_name='Paperless-ngx URL')),
                ('paperless_api_key', models.CharField(blank=True, default='', help_text='API-Token eines Paperless-Nutzers mit ausreichenden Berechtigungen.', max_length=200, verbose_name='Paperless-ngx API-Key')),
                ('module_dormitory', models.BooleanField(default=True, verbose_name='Wohnheimverwaltung')),
                ('module_inventory', models.BooleanField(default=True, verbose_name='Inventar')),
                ('module_absence', models.BooleanField(default=True, verbose_name='Abwesenheiten')),
                ('module_studyday', models.BooleanField(default=True, verbose_name='Lerntage')),
                ('module_assessment', models.BooleanField(default=True, verbose_name='Beurteilungen')),
                ('module_intervention', models.BooleanField(default=True, verbose_name='Maßnahmen')),
                ('module_announcements', models.BooleanField(default=True, verbose_name='Ankündigungen')),
                ('module_knowledge', models.BooleanField(default=True, verbose_name='Wissensdatenbank')),
                ('module_proofoftraining', models.BooleanField(default=True, verbose_name='Ausbildungsnachweise')),
                ('module_auditlog', models.BooleanField(default=True, verbose_name='Audit-Log')),
            ],
            options={
                'verbose_name': 'Website-Konfiguration',
                'verbose_name_plural': 'Website-Konfiguration',
            },
        ),
        migrations.CreateModel(
            name='AusbildungsreferatProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_manage_dormitory', models.BooleanField(default=False, verbose_name='Wohnheimverwaltung')),
                ('can_manage_inventory', models.BooleanField(default=False, verbose_name='Inventarverwaltung')),
                ('can_manage_absences', models.BooleanField(default=False, verbose_name='Abwesenheitsverwaltung')),
                ('can_approve_vacation', models.BooleanField(default=False, verbose_name='Urlaubsgenehmigung')),
                ('can_approve_study_days', models.BooleanField(default=False, verbose_name='Lerntage-Genehmigung')),
                ('can_manage_announcements', models.BooleanField(default=False, verbose_name='Ankündigungen verwalten')),
                ('can_manage_interventions', models.BooleanField(default=False, verbose_name='Maßnahmen verwalten')),
                ('job_profiles', models.ManyToManyField(blank=True, to='course.jobprofile', verbose_name='Zuständige Berufsbilder')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ausbildungsreferat_profile', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Ausbildungsreferat-Profil',
                'verbose_name_plural': 'Ausbildungsreferat-Profile',
            },
        ),
        migrations.CreateModel(
            name='CustomReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('category', models.CharField(default='Eigene Reports', max_length=60, verbose_name='Kategorie')),
                ('definition', models.JSONField(default=dict, help_text='JSON: datasource, select, filters, group_by, aggregations, order_by, limit.', verbose_name='Definition')),
                ('shared', models.BooleanField(default=False, verbose_name='Mit anderen Power-Usern teilen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_reports', to=settings.AUTH_USER_MODEL, verbose_name='Eigentümer')),
            ],
            options={
                'verbose_name': 'Eigener Report',
                'verbose_name_plural': 'Eigene Reports',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DashboardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_order', models.JSONField(default=list, help_text='Liste von Widget-IDs in gewünschter Reihenfolge.', verbose_name='Widget-Reihenfolge')),
                ('hidden_widgets', models.JSONField(default=list, help_text='Liste von Widget-IDs, die ausgeblendet sind.', verbose_name='Ausgeblendete Widgets')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_config', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Dashboard-Konfiguration',
                'verbose_name_plural': 'Dashboard-Konfigurationen',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300, verbose_name='Nachricht')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='Link')),
                ('icon', models.CharField(default='bi-bell', max_length=60, verbose_name='Icon')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Kategorie')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Gelesen am')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Empfänger')),
            ],
            options={
                'verbose_name': 'Interne Benachrichtigung',
                'verbose_name_plural': 'Interne Benachrichtigungen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedReportView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_slug', models.CharField(help_text='Verweist auf einen Code-Report aus services.reports.', max_length=100, verbose_name='Report-Slug')),
                ('name', models.CharField(max_length=120, verbose_name='Name der Sicht')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('filters_json', models.JSONField(blank=True, default=dict, help_text='Filter-Werte als JSON (Schlüssel = Filter-Key).', verbose_name='Filter-Konfiguration')),
                ('columns_json', models.JSONField(blank=True, default=list, help_text='Liste der sichtbaren Column-Keys in gewünschter Reihenfolge. Leer = alle.', verbose_name='Spalten-Auswahl')),
                ('shared', models.BooleanField(default=False, help_text='Wenn aktiv, sehen Ausbildungsleitung und -referat diese Sicht ebenfalls.', verbose_name='Mit anderen Power-Usern teilen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_report_views', to=settings.AUTH_USER_MODEL, verbose_name='Eigentümer')),
            ],
            options={
                'verbose_name': 'Gespeicherte Auswertungs-Sicht',
                'verbose_name_plural': 'Gespeicherte Auswertungs-Sichten',
                'ordering': ['report_slug', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disabled_keys', models.JSONField(default=list, help_text='Liste der deaktivierten Notification-Keys', verbose_name='Deaktivierte Benachrichtigungen')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'E-Mail-Präferenz',
                'verbose_name_plural': 'E-Mail-Präferenzen',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=200, verbose_name='Funktion')),
                ('room', models.CharField(blank=True, max_length=50, verbose_name='Raum')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Durchwahl')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisation.location', verbose_name='Standort')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Benutzerprofil',
                'verbose_name_plural': 'Benutzerprofile',
            },
        ),
    ]
