# Generated by Django 6.0.3 on 2026-05-06 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_adress_holiday_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('reset_user_2fa', 'Darf 2FA-Verknüpfungen anderer Benutzer zurücksetzen')], 'verbose_name': 'Benutzerprofil', 'verbose_name_plural': 'Benutzerprofile'},
        ),
    ]
