# Generated by Django 6.0.3 on 2026-05-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_inquiry_artifacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='key',
            field=models.CharField(choices=[('instructor_assignment', 'Praxistutor: Nachwuchskraft zugewiesen'), ('instructor_confirmed', 'Bestellungsschreiben: Praxistutor bestätigt'), ('instructor_confirmed_coordinator', 'Praxistutor bestätigt: Information an Koordination'), ('chief_assignment', 'Ausbildungskoordination: Einsatz angelegt/geändert'), ('chief_welcome', 'Willkommen: Benutzerkonto angelegt'), ('reminder_start', 'Erinnerung: Einsatz beginnt in 7 Tagen'), ('reminder_end', 'Erinnerung: Einsatz endet in 7 Tagen'), ('assignment_approved', 'Rückmeldung: Einsatz angenommen'), ('assignment_rejected', 'Rückmeldung: Einsatz abgelehnt'), ('practice_grade_confirmed', 'Bewertung: Praxisabschnitt bestätigt'), ('proof_of_training_approved', 'Ausbildungsnachweis: Angenommen'), ('proof_of_training_rejected', 'Ausbildungsnachweis: Korrekturbedarf'), ('proof_of_training_reminder', 'Erinnerung: Ausbildungsnachweis fehlt oder nicht eingereicht'), ('student_portal_welcome', 'Portal-Begrüßung: Zugangsdaten Nachwuchskraft'), ('study_day_approved', 'Lerntag: Antrag genehmigt'), ('study_day_rejected', 'Lerntag: Antrag abgelehnt'), ('study_day_cancelled', 'Lerntag: Genehmigter Tag storniert'), ('vacation_approved', 'Urlaub: Antrag genehmigt'), ('vacation_rejected', 'Urlaub: Antrag abgelehnt'), ('vacation_processed', 'Urlaub: Durch Urlaubsstelle bearbeitet'), ('inventory_issued', 'Inventar: Gegenstand ausgegeben'), ('inventory_returned', 'Inventar: Gegenstand zurückgegeben'), ('assessment_token_sent', 'Beurteilung: Link an Praxistutoren gesendet'), ('assessment_reminder', 'Beurteilung: Erinnerung an Praxistutoren (Stufe 1)'), ('assessment_reminder_urgent', 'Beurteilung: Dringende Erinnerung an Praxistutoren (Stufe 2)'), ('assessment_escalation', 'Beurteilung: Eskalation an Ausbildungskoordination (Stufe 3)'), ('assessment_submitted', 'Beurteilung: Praxistutoren hat eingereicht'), ('document_generated', 'Dokument: Bescheinigung erstellt'), ('change_request_submitted', 'Änderungsantrag: Neuer Antrag eingegangen'), ('change_request_approved', 'Änderungsantrag: Antrag genehmigt'), ('change_request_rejected', 'Änderungsantrag: Antrag abgelehnt'), ('assignment_decision_for_office', 'Praktikumseinsatz: Entscheidung der Koordination (Info Referat)')], max_length=50, unique=True, verbose_name='Typ'),
        ),
    ]
