# Generated by Django 6.0.3 on 2026-05-03 17:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRecordExportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('template_file', models.FileField(upload_to='proofoftraining/vorlagen/', verbose_name='Vorlage (.docx)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exportvorlage',
                'verbose_name_plural': 'Exportvorlagen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Öffentliche ID')),
                ('week_start', models.DateField(verbose_name='Wochenbeginn (Montag)')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('submitted', 'Eingereicht'), ('approved', 'Angenommen'), ('rejected', 'Korrekturbedarf')], default='draft', max_length=20, verbose_name='Status')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eingereicht am')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Geprüft am')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Korrekturhinweis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_training_records', to=settings.AUTH_USER_MODEL, verbose_name='Geprüft von')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to='student.student', verbose_name='Nachwuchskraft')),
            ],
            options={
                'verbose_name': 'Ausbildungsnachweis',
                'verbose_name_plural': 'Ausbildungsnachweise',
                'ordering': ['-week_start'],
                'unique_together': {('student', 'week_start')},
            },
        ),
        migrations.CreateModel(
            name='TrainingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum')),
                ('day_type', models.CharField(choices=[('praxis', 'Praktische Ausbildung'), ('schule', 'Berufsschule / Lehrveranstaltung'), ('sonstiges', 'Urlaub / Krank / Feiertag')], default='praxis', max_length=20, verbose_name='Art des Tages')),
                ('content', models.TextField(blank=True, verbose_name='Beschreibung der Tätigkeiten / Lerninhalte')),
                ('correction_note', models.TextField(blank=True, verbose_name='Korrekturhinweis (Prüfer)')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='proofoftraining.trainingrecord', verbose_name='Ausbildungsnachweis')),
            ],
            options={
                'verbose_name': 'Ausbildungstag',
                'verbose_name_plural': 'Ausbildungstage',
                'ordering': ['date'],
                'unique_together': {('record', 'date')},
            },
        ),
    ]
