# Generated by Django 6.0.3 on 2026-05-03 17:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChiefInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nachname')),
                ('email', models.EmailField(max_length=254, verbose_name='Dienstliche E-Mail')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Öffentliche ID')),
            ],
            options={
                'verbose_name': 'Person (Ausbildungskoordination)',
                'verbose_name_plural': 'Personen (Ausbildungskoordination)',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Öffentliche ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nachname')),
                ('email', models.EmailField(max_length=254, verbose_name='Dienstliche E-Mail')),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('confirmed', 'Bestätigt')], default='pending', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Praxistutor',
                'verbose_name_plural': 'Praxistutoren',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='InstructorOrderTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('template_file', models.FileField(upload_to='instructor/templates/', verbose_name='Vorlage (.docx)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('uploaded_at', models.DateTimeField(auto_now=True, verbose_name='Hochgeladen am')),
            ],
            options={
                'verbose_name': 'Bestellungsvorlage Praxistutor',
                'verbose_name_plural': 'Bestellungsvorlagen Praxistutor',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingCoordination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Öffentliche ID')),
                ('name', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('functional_email', models.EmailField(blank=True, help_text='Gemeinsames Postfach aller Mitglieder (z. B. 4_ausbildung@…). Zuweisungs-E-Mails werden hierhin gesendet.', max_length=254, verbose_name='Funktionspostfach')),
            ],
            options={
                'verbose_name': 'Ausbildungskoordination',
                'verbose_name_plural': 'Ausbildungskoordinationen',
                'db_table': 'instructor_koordination',
                'ordering': ['name'],
            },
        ),
    ]
