# Generated by Django 6.0.3 on 2026-05-03 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0002_initial'),
        ('instructor', '0001_initial'),
        ('organisation', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chiefinstructor',
            name='salutation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.gender', verbose_name='Anrede'),
        ),
        migrations.AddField(
            model_name='chiefinstructor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chief_instructor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Benutzerkonto'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='job_profiles',
            field=models.ManyToManyField(blank=True, related_name='instructors', to='course.jobprofile', verbose_name='Berufsbilder'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructors', to='organisation.location', verbose_name='Standort'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='salutation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.gender', verbose_name='Anrede'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructors', to='organisation.organisationalunit', verbose_name='Organisationseinheit'),
        ),
        migrations.AddField(
            model_name='trainingcoordination',
            name='units',
            field=models.ManyToManyField(blank=True, related_name='training_coordinations', to='organisation.organisationalunit', verbose_name='Organisationseinheiten'),
        ),
        migrations.AddField(
            model_name='chiefinstructor',
            name='coordination',
            field=models.ForeignKey(blank=True, db_column='koordination_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='instructor.trainingcoordination', verbose_name='Ausbildungskoordination'),
        ),
    ]
