# Generated by Django 6.0.3 on 2026-05-03 17:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Öffentliche ID')),
                ('name', models.CharField(max_length=100, verbose_name='Bezeichnung')),
                ('icon', models.CharField(blank=True, default='bi-box', help_text='z. B. bi-laptop, bi-credit-card-2-front, bi-key', max_length=50, verbose_name='Bootstrap-Icon')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorien',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Öffentliche ID')),
                ('name', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Seriennummer / Kennung')),
                ('status', models.CharField(choices=[('verfuegbar', 'Verfügbar'), ('ausgegeben', 'Ausgegeben'), ('defekt', 'Defekt'), ('ausgemustert', 'Ausgemustert')], default='verfuegbar', max_length=20, verbose_name='Status')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Lagerort')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gegenstand',
                'verbose_name_plural': 'Gegenstände',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Öffentliche ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('template_file', models.FileField(help_text='Verfügbare Platzhalter: {{ vorname }}, {{ nachname }}, {{ student_id }}, {{ gegenstand }}, {{ seriennummer }}, {{ kategorie }}, {{ ausgabedatum }}, {{ ausgegeben_von }}, {{ heute }}', upload_to='inventory/templates/', verbose_name='Vorlage (.docx)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('uploaded_at', models.DateTimeField(auto_now=True, verbose_name='Hochgeladen am')),
            ],
            options={
                'verbose_name': 'Ausgabequittungs-Vorlage',
                'verbose_name_plural': 'Ausgabequittungs-Vorlagen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryIssuance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Öffentliche ID')),
                ('issued_at', models.DateTimeField(verbose_name='Ausgabedatum/-uhrzeit')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='Rückgabedatum/-uhrzeit')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('scanned_receipt_paperless_id', models.PositiveIntegerField(blank=True, help_text='Paperless-Dokument-ID der eingescannten, unterschriebenen Quittung.', null=True, verbose_name='Eingescannte Quittung (Paperless-ID)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_issuances_made', to=settings.AUTH_USER_MODEL, verbose_name='Ausgegeben von')),
                ('returned_acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_returns_acknowledged', to=settings.AUTH_USER_MODEL, verbose_name='Rückgabe bestätigt von')),
            ],
            options={
                'verbose_name': 'Ausgabe',
                'verbose_name_plural': 'Ausgaben',
                'ordering': ['-issued_at'],
            },
        ),
    ]
