# Generated by Django 6.0.3 on 2026-05-03 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryissuance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_issuances', to='student.student', verbose_name='Nachwuchskraft'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.inventorycategory', verbose_name='Kategorie'),
        ),
        migrations.AddField(
            model_name='inventoryissuance',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issuances', to='inventory.inventoryitem', verbose_name='Gegenstand'),
        ),
        migrations.AddField(
            model_name='inventorycategory',
            name='receipt_template',
            field=models.ForeignKey(blank=True, help_text='Vorlage, die bei der Ausgabe von Gegenständen dieser Kategorie verwendet wird.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='inventory.receipttemplate', verbose_name='Ausgabequittungs-Vorlage'),
        ),
    ]
