# SPDX-License-Identifier: EUPL-1.2
# SPDX-FileCopyrightText: 2026 devNicoLax
"""
Django settings for Azubi project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import locale
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Versionsnummer aus VERSION-Datei im Projektstamm
APP_VERSION = (BASE_DIR / 'VERSION').read_text(encoding='utf-8').strip()

load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',') if os.environ.get('ALLOWED_HOSTS') else []
CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if os.environ.get('CSRF_TRUSTED_ORIGINS') else []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.openid_connect',
    'dbbackup',
    'student.apps.StudentConfig',
    'course.apps.CourseConfig',
    'document.apps.DocumentConfig',
    'services.apps.ServicesConfig',
    'dormitory.apps.DormitoryConfig',
    'organisation.apps.OrganisationConfig',
    'instructor.apps.InstructorConfig',
    'proofoftraining.apps.ProofoftrainingConfig',
    'auditlog.apps.AuditlogConfig',
    'portal.apps.PortalConfig',
    'studyday.apps.StudydayConfig',
    'inventory.apps.InventoryConfig',
    'absence.apps.AbsenceConfig',
    'assessment.apps.AssessmentConfig',
    'intervention.apps.InterventionConfig',
    'announcements.apps.AnnouncementsConfig',
    'knowledge.apps.KnowledgeConfig',
    'django_celery_beat',
    'workspace.apps.WorkspaceConfig',
    'mandatorytraining.apps.MandatorytrainingConfig',
    'axes',
    'django_otp',
    'django_otp.plugins.otp_totp',     # TOTP (Authenticator-App)
    'django_otp.plugins.otp_static',   # Recovery-Codes
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # OTP-Middleware muss direkt nach AuthenticationMiddleware laufen,
    # damit request.user.is_verified() in nachfolgenden Views verfügbar ist.
    'django_otp.middleware.OTPMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'services.middleware.RoleAccessMiddleware',
    'services.middleware.ModuleAccessMiddleware',
    'auditlog.middleware.AuditLogMiddleware',
    # allauth-Pflichtmiddleware: hängt SocialAccount-State an den Request.
    'allauth.account.middleware.AccountMiddleware',
    # AxesMiddleware muss als letztes laufen, damit alle vorherigen Middleware-
    # Errors abgefangen wurden, bevor Lockout-Logik greift.
    'axes.middleware.AxesMiddleware',
]

ROOT_URLCONF = 'Azubi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'services.context_processors.roles',
                'services.context_processors.site_config',
            ],
        },
    },
]

WSGI_APPLICATION = 'Azubi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'postgres'),
        'USER': os.environ.get('DB_USER', 'myuser'),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 12},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'services.password_validators.SymbolAndDigitValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'de-de'
TIME_ZONE = 'Europe/Berlin'

USE_I18N = True
USE_TZ = True

LOCALE_NAME = 'de_DE.UTF-8'
try:
    locale.setlocale(locale.LC_ALL, 'de_DE.UTF-8')
except locale.Error:
    try:
        locale.setlocale(locale.LC_ALL, 'de_DE')
    except locale.Error:
        locale.setlocale(locale.LC_ALL, '')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "Azubi.storage.ManifestStaticFilesStorage"},
}
MEDIA_URL  = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

SESSION_COOKIE_NAME = "azubi_session"
CSRF_COOKIE_NAME   = "azubi_csrftoken"

PAPERLESS_URL = os.environ.get('PAPERLESS_URL', '')
PAPERLESS_API_KEY = os.environ.get('PAPERLESS_API_KEY', '')

# E-Mail (SMTP)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'False') == 'True'
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', '')
DEFAULT_REPLY_TO_EMAIL = os.environ.get('DEFAULT_REPLY_TO_EMAIL', '')

# iCal-UID-Domain für Outlook-Termin-Anhänge (RFC 5545 UID muss global eindeutig sein).
# Default fällt auf den Domain-Teil von DEFAULT_FROM_EMAIL zurück, auch wenn dieser
# im Format "Anzeigename <user@domain.tld>" konfiguriert ist.
CALENDAR_UID_DOMAIN = os.environ.get('CALENDAR_UID_DOMAIN') or (
    DEFAULT_FROM_EMAIL.rsplit('@', 1)[-1].strip(' <>')
    if '@' in DEFAULT_FROM_EMAIL else 'azubi.local'
)

# Auth
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# AxesStandaloneBackend muss vor allen anderen stehen: er wirft
# AxesBackendPermissionDenied bei gesperrtem Konto, bevor andere Backends
# überhaupt das Passwort/Token prüfen.
# LocalOnlyModelBackend ersetzt das Default-ModelBackend und sperrt
# Lokal-Login für User mit verknüpfter externer Identität (SSO-User).
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'services.auth_backends.LocalOnlyModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# allauth braucht django.contrib.sites; eine Site genügt für unseren Single-Tenant-Betrieb.
SITE_ID = 1

# ---------------------------------------------------------------------------
# django-allauth – Social-/OIDC-Konfiguration
# ---------------------------------------------------------------------------
# Wir nutzen NUR den socialaccount-Teil von allauth (OIDC für Behörden-Logins).
# Lokales Login, Passwort-Reset etc. laufen weiterhin über django.contrib.auth –
# die zugehörigen allauth-URLs bleiben unter /sso/ erreichbar, werden aber
# nicht in die Login-UI verlinkt.
#
# Kein automatisches Anlegen unbekannter User: SSO darf nur authentifizieren,
# niemals provisionieren. Das Matching auf bestehende lokale Konten erfolgt
# in Schritt 4 über einen Custom-Adapter (E-Mail + Domain-Whitelist).
SOCIALACCOUNT_AUTO_SIGNUP = False
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'  # IdP hat E-Mail bereits verifiziert
SOCIALACCOUNT_QUERY_EMAIL = True
# Wir aktivieren bewusst NICHT SOCIALACCOUNT_LOGIN_ON_GET. Stattdessen rendert
# unsere `sso_start`-View ein Auto-Submit-POST-Formular gegen die allauth-
# Login-URL: Login-CSRF-Schutz bleibt aktiv, aber das User-Experience-Problem
# (rohes Interstitial) entfällt.
SOCIALACCOUNT_ADAPTER = 'services.sso_adapter.AzubiSocialAccountAdapter'

# allauth-Account-Settings: irrelevant, da wir die lokalen Login-Flows nicht
# über allauth, sondern weiterhin über django.contrib.auth bedienen. Wir
# setzen Defaults aber ausdrücklich, damit nichts versehentlich greift.
ACCOUNT_EMAIL_VERIFICATION = 'none'

# ---------------------------------------------------------------------------
# django-otp – TOTP-Aussteller in Authenticator-Apps
# ---------------------------------------------------------------------------
# Wird beim Scannen des QR-Codes als "Aussteller" / "Issuer" hinterlegt
# (sonst zeigt Google/Microsoft Authenticator "Kein Aussteller" an).
# Callable, damit der Wert aus SiteConfiguration.brand_name kommt – ändert
# sich der App-Name in den Einstellungen, gilt das auch für künftig
# eingerichtete 2FA-Geräte.
def _otp_totp_issuer(device):
    try:
        from services.models import SiteConfiguration
        name = (SiteConfiguration.get().brand_name or '').strip()
        return name or 'Azubi-Portal'
    except Exception:
        return 'Azubi-Portal'

OTP_TOTP_ISSUER = _otp_totp_issuer

# ---------------------------------------------------------------------------
# django-axes – Brute-Force-Schutz für Lokal-Login
# ---------------------------------------------------------------------------
# Sperrt nach FAILURE_LIMIT Fehlversuchen die Kombination aus Benutzername + IP
# für COOLOFF_TIME. Erfolgreiche Anmeldung setzt Zähler auf 0.
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 0.25  # Stunden = 15 Minuten
AXES_RESET_ON_SUCCESS = True
# Kombinations-Lock: nur derselbe User von derselben IP wird gesperrt.
# Verhindert, dass ein Angreifer fremde Konten via IP-Spoofing aussperrt
# und dass mehrere Behörden-Mitarbeiter hinter einer NAT-IP sich gegenseitig sperren.
AXES_LOCKOUT_PARAMETERS = [['username', 'ip_address']]
AXES_LOCKOUT_TEMPLATE = 'registration/account_locked.html'
AXES_VERBOSE = True
# Zusätzlicher Audit-Log: jeder einzelne Fehlversuch wird in AccessFailureLog
# geschrieben (auch unterhalb der Lockout-Schwelle). Im Admin sichtbar unter
# "Fehlgeschlagene Zugriffe". Lockouts liegen weiterhin in AccessAttempt.
AXES_ENABLE_ACCESS_FAILURE_LOG = True
# Login-Form-Feld, aus dem axes den Benutzernamen extrahiert
AXES_USERNAME_FORM_FIELD = 'username'
# Passwort niemals in Logs / Signal-Payloads schreiben
AXES_SENSITIVE_PARAMETERS = ['password']

# ---------------------------------------------------------------------------
# Cache (Redis, separate DB von Celery-Broker/Result)
# ---------------------------------------------------------------------------
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': os.environ.get('REDIS_CACHE_URL', 'redis://localhost:6379/2'),
        'KEY_PREFIX': 'azubi',
        'TIMEOUT': 300,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'IGNORE_EXCEPTIONS': True,  # Redis-Ausfall darf Requests nicht killen
        },
    },
}
DJANGO_REDIS_IGNORE_EXCEPTIONS = True

# ---------------------------------------------------------------------------
# Celery
# ---------------------------------------------------------------------------
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379/1')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_WORKER_POOL = 'solo'  # Vermeidet SIGSEGV mit Python 3.14 auf macOS (kein fork)
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True  # Unterdrückt CPendingDeprecationWarning

# Beat liest seinen Zeitplan aus der DB (django-celery-beat). Änderungen an
# SiteConfiguration werden per post_save-Signal in PeriodicTask synchronisiert
# und vom Beat-Worker innerhalb weniger Sekunden ohne Neustart übernommen.
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Basis-URL für Links in Task-E-Mails (kein request-Objekt verfügbar)
SITE_BASE_URL = os.environ.get('SITE_BASE_URL', 'http://localhost:8000')

# ---------------------------------------------------------------------------
# Backup (django-dbbackup)
# ---------------------------------------------------------------------------
# Lokales Bind-Mount-Verzeichnis. In Produktion zeigt /backups auf einen
# Host-Bind-Mount (z. B. /var/backups/azubi), den ein restic-Job off-site
# auf NAS spiegelt. So bleibt pg_dump atomar auf lokalem FS und überlebt
# kurzzeitige Netzwerk-Probleme.
BACKUP_DIR = os.environ.get('BACKUP_DIR', str(BASE_DIR / 'backups'))
os.makedirs(BACKUP_DIR, exist_ok=True)

DBBACKUP_STORAGE = 'django.core.files.storage.FileSystemStorage'
DBBACKUP_STORAGE_OPTIONS = {'location': BACKUP_DIR}
DBBACKUP_CONNECTORS = {
    'default': {
        'CONNECTOR': 'dbbackup.db.postgresql.PgDumpBinaryConnector',
        # Custom-Format: schneller, selektiver Restore möglich, komprimiert
        'SINGLE_TRANSACTION': False,
    },
}
DBBACKUP_FILENAME_TEMPLATE = 'azubi-{datetime}.{extension}'
DBBACKUP_MEDIA_FILENAME_TEMPLATE = 'azubi-media-{datetime}.{extension}'
DBBACKUP_DATE_FORMAT = '%Y%m%d-%H%M%S'
DBBACKUP_CLEANUP_KEEP = int(os.environ.get('BACKUP_KEEP_DAILY', '7'))
DBBACKUP_CLEANUP_KEEP_MEDIA = int(os.environ.get('BACKUP_KEEP_DAILY', '7'))
# Ältere Backups (>30 Tage) übernimmt die GFS-Rotation der Cleanup-Task.
DBBACKUP_SEND_EMAIL = False  # Wir versenden Fehler-Mails selbst über services.send_mail_task

# Paperless-Backup-Pfade (werden im docker-compose als Bind-Mount gemountet)
PAPERLESS_EXPORT_DIR = os.environ.get('PAPERLESS_EXPORT_DIR', str(BASE_DIR / 'paperless' / 'export'))

# ---------------------------------------------------------------------------
# Sicherheits-Header (nur in Produktion aktivieren)
# ---------------------------------------------------------------------------
# DEBUG=True überspringt diese Einstellungen, damit lokale Entwicklung ohne
# HTTPS funktioniert. In Produktion (DEBUG=False) werden alle Header aktiv.
if not DEBUG:
    # Cookies nur über HTTPS senden
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # HTTP automatisch auf HTTPS umleiten (Reverse-Proxy muss X-Forwarded-Proto setzen)
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # HSTS: Browser zwingen, ein Jahr lang nur HTTPS zu nutzen
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 365  # 1 Jahr
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # MIME-Type-Sniffing in Browsern unterbinden
    SECURE_CONTENT_TYPE_NOSNIFF = True

    # Referrer-Policy: keine Referrer an externe Seiten senden
    SECURE_REFERRER_POLICY = 'same-origin'

    # Cross-Origin-Opener-Policy: Tab-Isolation gegen Spectre-Side-Channel
    SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'

    # Hinter Reverse-Proxy: Client-IP aus X-Forwarded-For lesen (sonst sieht
    # axes nur die Proxy-IP und sperrt im Zweifel alle User gemeinsam).
    AXES_IPWARE_PROXY_COUNT = 1
    AXES_IPWARE_META_PRECEDENCE_ORDER = ('HTTP_X_FORWARDED_FOR', 'REMOTE_ADDR')

# Clickjacking-Schutz (immer, auch in Entwicklung)
X_FRAME_OPTIONS = 'DENY'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}
