# Generated by Django 6.0.3 on 2026-05-03 17:50

import django.db.models.deletion
import services.storage
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=services.storage.uuid_upload_to('announcements/attachments/'), verbose_name='Datei')),
                ('filename', models.CharField(blank=True, max_length=255, verbose_name='Dateiname')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Anhang',
                'verbose_name_plural': 'Anhänge',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Gelesen am')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Bestätigt am')),
            ],
            options={
                'verbose_name': 'Empfänger',
                'verbose_name_plural': 'Empfänger',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Öffentliche ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('body', models.TextField(verbose_name='Inhalt (HTML)')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('published', 'Veröffentlicht')], default='draft', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Veröffentlicht am')),
                ('requires_acknowledgement', models.BooleanField(default=False, help_text='Empfänger müssen den Erhalt aktiv bestätigen.', verbose_name='Bestätigung erforderlich')),
                ('send_email', models.BooleanField(default=True, help_text='Beim Veröffentlichen eine E-Mail an alle Empfänger senden.', verbose_name='Per E-Mail versenden')),
                ('target_type', models.CharField(choices=[('all_students', 'Alle Nachwuchskräfte'), ('course', 'Bestimmter Kurs'), ('job_profile', 'Bestimmtes Berufsbild'), ('koordination', 'Bestimmte Koordination'), ('career', 'Bestimmte Laufbahn'), ('individual', 'Einzelne Nachwuchskräfte')], default='all_students', max_length=20, verbose_name='Zielgruppe')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_announcements', to=settings.AUTH_USER_MODEL, verbose_name='Absender')),
            ],
            options={
                'verbose_name': 'Ankündigung',
                'verbose_name_plural': 'Ankündigungen',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
