# Generated by Django 6.0.3 on 2026-05-03 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('announcements', '0002_initial'),
        ('course', '0001_initial'),
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='target_coordination',
            field=models.ForeignKey(blank=True, db_column='target_koordination_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='instructor.trainingcoordination', verbose_name='Ziel-Koordination'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='course.course', verbose_name='Ziel-Kurs'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_job_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='course.jobprofile', verbose_name='Ziel-Berufsbild'),
        ),
    ]
