# Generated by Django 6.0.3 on 2026-05-03 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('announcements', '0003_initial'),
        ('student', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='target_students',
            field=models.ManyToManyField(blank=True, related_name='+', to='student.student', verbose_name='Einzelne Nachwuchskräfte'),
        ),
        migrations.AddField(
            model_name='announcementattachment',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='announcements.announcement', verbose_name='Ankündigung'),
        ),
        migrations.AddField(
            model_name='announcementrecipient',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='announcements.announcement', verbose_name='Ankündigung'),
        ),
        migrations.AddField(
            model_name='announcementrecipient',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_announcements', to=settings.AUTH_USER_MODEL, verbose_name='Empfänger'),
        ),
        migrations.AlterUniqueTogether(
            name='announcementrecipient',
            unique_together={('announcement', 'user')},
        ),
    ]
