# Generated by Django 6.0.3 on 2026-05-03 17:50

import django.core.validators
import django.db.models.deletion
import services.storage
import student.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('organisation', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('type', models.AutoField(primary_key=True, serialize=False, verbose_name='Art')),
                ('description', models.CharField(max_length=100, verbose_name='Beschreibung')),
            ],
            options={
                'verbose_name': 'Beschäftigungsverhältnis',
                'verbose_name_plural': 'Beschäftigungsverhältnisse',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100, verbose_name='Beschreibung')),
                ('color', models.CharField(choices=[('success', 'Grün'), ('secondary', 'Grau'), ('danger', 'Rot'), ('warning', 'Gelb'), ('info', 'Blau')], default='secondary', max_length=20, verbose_name='Farbe')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='StudentDocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Verfügbare Platzhalter – Nachwuchskraft: {{ vorname }}, {{ nachname }}, {{ student_id }}, {{ geburtsdatum }}, {{ geburtsort }}, {{ email_privat }}, {{ email_dienstlich }}, {{ telefon }} | Kurs: {{ kurs }}, {{ kurs_beginn }}, {{ kurs_ende }} | Berufsbild: {{ berufsbild }}, {{ berufsbild_beschreibung }}, {{ abschluss }}, {{ gesetzesgrundlage }}, {{ laufbahn }}, {{ fachrichtung }} | Meta: {{ heute }}, {{ erstellt_von }}, {{ ersteller_funktion }}, {{ ersteller_standort }}, {{ ersteller_raum }}, {{ ersteller_durchwahl }}', verbose_name='Beschreibung')),
                ('template_file', models.FileField(upload_to='student/dokument_vorlagen/', verbose_name='Vorlage (.docx)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('available_in_portal', models.BooleanField(default=False, help_text='Nachwuchskräfte können dieses Dokument selbst im Portal generieren.', verbose_name='Im Portal verfügbar')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dokumentvorlage',
                'verbose_name_plural': 'Dokumentvorlagen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Feldname')),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Zahl'), ('date', 'Datum'), ('boolean', 'Ja/Nein')], default='text', max_length=20, verbose_name='Feldtyp')),
            ],
            options={
                'verbose_name': 'Benutzerdefiniertes Feld',
                'verbose_name_plural': 'Benutzerdefinierte Felder',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('job_profiles', models.ManyToManyField(blank=True, help_text='Leer lassen = für alle Berufsbilder verfügbar.', related_name='checklist_templates', to='course.jobprofile', verbose_name='Berufsbilder')),
            ],
            options={
                'verbose_name': 'Checklisten-Vorlage',
                'verbose_name_plural': 'Checklisten-Vorlagen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Aufgabe')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='student.checklisttemplate', verbose_name='Vorlage')),
            ],
            options={
                'verbose_name': 'Checklisten-Punkt (Vorlage)',
                'verbose_name_plural': 'Checklisten-Punkte (Vorlage)',
                'ordering': ['template', 'order', 'text'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(default=student.models.create_student_id, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nachname')),
                ('date_of_birth', models.DateField(verbose_name='Geburtsdatum')),
                ('place_of_birth', models.CharField(max_length=100, verbose_name='Geburtsort')),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='Telefonnummer')),
                ('email_private', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail (privat)')),
                ('email_id', models.CharField(blank=True, max_length=254, null=True, verbose_name='E-Mail-Kennung (dienstlich)')),
                ('status_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='Status geändert am')),
                ('anonymized_at', models.DateTimeField(blank=True, null=True, verbose_name='Anonymisiert am')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Geändert am')),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.adress', verbose_name='Adresse')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='course.course', verbose_name='Kurs')),
                ('employment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.employment', verbose_name='Beschäftigungsverhältnis')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.gender', verbose_name='Geschlecht')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.status', verbose_name='Status')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Portal-Benutzerkonto')),
            ],
            options={
                'verbose_name': 'Nachwuchskraft',
                'verbose_name_plural': 'Nachwuchskräfte',
            },
        ),
        migrations.CreateModel(
            name='InternshipPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Freitext für individuelle Wünsche.', verbose_name='Weitere Wünsche / Anmerkungen')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('preferred_locations', models.ManyToManyField(blank=True, related_name='preferred_by_students', to='organisation.location', verbose_name='Gewünschte Standorte')),
                ('preferred_units', models.ManyToManyField(blank=True, help_text='Nur Ebene Abteilung oder Behörde.', limit_choices_to={'unit_type__in': ['authority', 'department']}, related_name='preferred_by_students', to='organisation.organisationalunit', verbose_name='Gewünschte Abteilungen / Behörden')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='internship_preference', to='student.student', verbose_name='Nachwuchskraft')),
            ],
            options={
                'verbose_name': 'Einsatzwunsch',
                'verbose_name_plural': 'Einsatzwünsche',
            },
        ),
        migrations.CreateModel(
            name='InternalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Öffentliche ID')),
                ('text', models.TextField(verbose_name='Notiz')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Angepinnt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Geändert am')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_notes', to='student.student', verbose_name='Nachwuchskraft')),
            ],
            options={
                'verbose_name': 'Interne Notiz',
                'verbose_name_plural': 'Interne Notizen',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Öffentliche ID')),
                ('value', models.CharField(blank=True, help_text='z. B. 1,5 oder 87 Punkte', max_length=20, verbose_name='Note')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Datum')),
                ('notes', models.TextField(blank=True, verbose_name='Anmerkungen')),
                ('paperless_document_id', models.IntegerField(blank=True, null=True, verbose_name='Paperless-Dokument-ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grade_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='course.gradetype', verbose_name='Notenart')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='student.student', verbose_name='Nachwuchskraft')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Noten',
                'ordering': ['grade_type__order', 'grade_type__name', '-date'],
            },
        ),
        migrations.CreateModel(
            name='ContactEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Öffentliche ID')),
                ('contact_type', models.CharField(choices=[('phone', 'Telefonisch'), ('on_site', 'Vor Ort'), ('email', 'E-Mail')], max_length=20, verbose_name='Art')),
                ('inquiry', models.TextField(verbose_name='Anfrage / Anliegen')),
                ('response', models.TextField(blank=True, verbose_name='Gegebene Antwort')),
                ('contacted_at', models.DateTimeField(verbose_name='Kontaktzeitpunkt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Erfasst von')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_entries', to='student.student', verbose_name='Nachwuchskraft')),
            ],
            options={
                'verbose_name': 'Kontakteintrag',
                'verbose_name_plural': 'Kontakteinträge',
                'ordering': ['-contacted_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Öffentliche ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='student.student', verbose_name='Nachwuchskraft')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.checklisttemplate', verbose_name='Vorlage')),
            ],
            options={
                'verbose_name': 'Checkliste',
                'verbose_name_plural': 'Checklisten',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Öffentliche ID')),
                ('text', models.CharField(max_length=300, verbose_name='Aufgabe')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('completed', models.BooleanField(default=False, verbose_name='Erledigt')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Erledigt am')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='student.studentchecklist', verbose_name='Checkliste')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_checklist_items', to=settings.AUTH_USER_MODEL, verbose_name='Erledigt von')),
            ],
            options={
                'verbose_name': 'Checklisten-Punkt',
                'verbose_name_plural': 'Checklisten-Punkte',
                'ordering': ['order', 'text'],
            },
        ),
        migrations.CreateModel(
            name='StudentInquiry',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200, verbose_name='Betreff')),
                ('message', models.TextField(verbose_name='Nachricht')),
                ('attachment', models.FileField(blank=True, upload_to=services.storage.uuid_upload_to('inquiries/attachments/'), verbose_name='Anhang')),
                ('attachment_filename', models.CharField(blank=True, max_length=255, verbose_name='Originalname des Anhangs')),
                ('status', models.CharField(choices=[('open', 'Offen'), ('in_progress', 'In Bearbeitung'), ('closed', 'Geschlossen')], default='open', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='student.student', verbose_name='Nachwuchskraft')),
            ],
            options={
                'verbose_name': 'Anfrage',
                'verbose_name_plural': 'Anfragen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InquiryReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Nachricht')),
                ('attachment', models.FileField(blank=True, upload_to=services.storage.uuid_upload_to('inquiries/attachments/'), verbose_name='Anhang')),
                ('attachment_filename', models.CharField(blank=True, max_length=255, verbose_name='Originalname des Anhangs')),
                ('is_staff_reply', models.BooleanField(default=False, verbose_name='Antwort vom Personal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Verfasser')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='student.studentinquiry', verbose_name='Anfrage')),
            ],
            options={
                'verbose_name': 'Antwort',
                'verbose_name_plural': 'Antworten',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentDocumentTemplateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Wird in der Word-Vorlage als {{ schlüssel }} verwendet.', max_length=64, validators=[django.core.validators.RegexValidator(message='Nur Kleinbuchstaben, Zahlen und Unterstriche; muss mit einem Buchstaben beginnen.', regex='^[a-z][a-z0-9_]*$')], verbose_name='Schlüssel')),
                ('label', models.CharField(max_length=200, verbose_name='Beschriftung')),
                ('field_type', models.CharField(choices=[('text', 'Text (einzeilig)'), ('textarea', 'Text (mehrzeilig)'), ('date', 'Datum'), ('number', 'Zahl'), ('select', 'Auswahl-Liste')], default='text', max_length=20, verbose_name='Feldtyp')),
                ('required', models.BooleanField(default=False, verbose_name='Pflichtfeld')),
                ('help_text', models.CharField(blank=True, max_length=200, verbose_name='Hilfetext')),
                ('options', models.TextField(blank=True, help_text='Bei Auswahl-Liste: eine Option pro Zeile.', verbose_name='Optionen')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_fields', to='student.studentdocumenttemplate', verbose_name='Dokumentvorlage')),
            ],
            options={
                'verbose_name': 'Vorlagenfeld',
                'verbose_name_plural': 'Vorlagenfelder',
                'ordering': ['order', 'pk'],
                'unique_together': {('template', 'key')},
            },
        ),
        migrations.CreateModel(
            name='StudentFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, verbose_name='Wert')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentfielddefinition', verbose_name='Feld')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='student.student')),
            ],
            options={
                'verbose_name': 'Feldwert',
                'verbose_name_plural': 'Feldwerte',
                'unique_together': {('student', 'field')},
            },
        ),
        migrations.CreateModel(
            name='TrainingResponsibleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_responsible_access_granted', to=settings.AUTH_USER_MODEL, verbose_name='Erteilt von')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_responsible_access_grants', to='student.student')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_responsible_student_access', to=settings.AUTH_USER_MODEL, verbose_name='Ausbildungsverantwortliche-Benutzer')),
            ],
            options={
                'verbose_name': 'Ausbildungsverantwortliche-Zugriff',
                'verbose_name_plural': 'Ausbildungsverantwortliche-Zugriffe',
                'db_table': 'student_personalstelleaccess',
                'unique_together': {('student', 'user')},
            },
        ),
    ]
