# Generated by Django 6.0.3 on 2026-05-03 17:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisation', '0001_initial'),
        ('student', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Bezeichnung')),
                ('icon', models.CharField(blank=True, default='bi-door-closed', help_text='Bootstrap-Icon-Klasse, z.B. "bi-door-closed", "bi-people".', max_length=50, verbose_name='Bootstrap-Icon')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Arbeitsplatz-Typ',
                'verbose_name_plural': 'Arbeitsplatz-Typen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Bezeichnung')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Öffentliche ID')),
                ('capacity', models.PositiveIntegerField(default=1, help_text='Anzahl gleichzeitig möglicher Buchungen pro Tag (1 für Einzelbüro, mehr für Lerninseln).', verbose_name='Kapazität')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('equipment', models.TextField(blank=True, help_text='Freitext, z.B. „1x PC, 2x Monitor, Whiteboard".', verbose_name='Ausstattung')),
                ('booking_horizon_days', models.PositiveIntegerField(default=28, help_text='Wie viele Tage im Voraus dürfen Buchungen angelegt werden?', verbose_name='Buchungs-Horizont (Tage)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv (buchbar)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workspaces', to='organisation.location', verbose_name='Standort')),
                ('unit', models.ForeignKey(blank=True, help_text='Optional: zugeordnete Einheit (rein informativ).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspaces', to='organisation.organisationalunit', verbose_name='Organisationseinheit')),
                ('workspace_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workspaces', to='workspace.workspacetype', verbose_name='Typ')),
            ],
            options={
                'verbose_name': 'Arbeitsplatz',
                'verbose_name_plural': 'Arbeitsplätze',
                'ordering': ['location__name', 'workspace_type__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Öffentliche ID')),
                ('start_date', models.DateField(verbose_name='Von')),
                ('end_date', models.DateField(verbose_name='Bis')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Grund')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closures', to='workspace.workspace', verbose_name='Arbeitsplatz')),
            ],
            options={
                'verbose_name': 'Sperrzeitraum',
                'verbose_name_plural': 'Sperrzeiträume',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Öffentliche ID')),
                ('date', models.DateField(verbose_name='Datum')),
                ('purpose', models.CharField(blank=True, help_text='Optional: kurzer Verwendungszweck.', max_length=200, verbose_name='Zweck')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('status', models.CharField(choices=[('confirmed', 'Bestätigt'), ('cancelled', 'Storniert')], default='confirmed', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Storniert am')),
                ('notification_sequence', models.PositiveIntegerField(default=0, help_text='Wird bei Stornierung erhöht; Outlook erkennt Updates über UID + SEQUENCE.', verbose_name='iCal-Sequenznummer')),
                ('booked_by', models.ForeignKey(help_text='Konto, das die Buchung angelegt hat (Nachwuchskraft selbst oder Koordination).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_bookings_made', to=settings.AUTH_USER_MODEL, verbose_name='Gebucht von')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_bookings_cancelled', to=settings.AUTH_USER_MODEL, verbose_name='Storniert von')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_bookings', to='student.student', verbose_name='Nachwuchskraft')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='workspace.workspace', verbose_name='Arbeitsplatz')),
            ],
            options={
                'verbose_name': 'Raumbuchung',
                'verbose_name_plural': 'Raumbuchungen',
                'ordering': ['-date', 'workspace__name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'confirmed')), fields=('workspace', 'student', 'date'), name='uniq_active_workspace_booking')],
            },
        ),
    ]
