# Generated by Django 6.0.3 on 2026-05-03 17:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Öffentliche ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Bezeichnung')),
                ('escalation_level', models.PositiveSmallIntegerField(default=1, help_text='1 = niedrig, 2 = mittel, 3 = hoch, 4 = kritisch', verbose_name='Eskalationsstufe')),
                ('color', models.CharField(choices=[('secondary', 'Grau'), ('primary', 'Blau'), ('info', 'Hellblau'), ('success', 'Grün'), ('warning', 'Gelb'), ('danger', 'Rot'), ('dark', 'Dunkel')], default='secondary', max_length=20, verbose_name='Farbe')),
                ('requires_followup', models.BooleanField(default=False, help_text='Wenn aktiv, muss bei der Maßnahme eine Frist angegeben werden.', verbose_name='Folgetermin erforderlich')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Maßnahmen-Kategorie',
                'verbose_name_plural': 'Maßnahmen-Kategorien',
                'ordering': ['escalation_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Öffentliche ID')),
                ('trigger_type', models.CharField(choices=[('absence', 'Fehlzeiten'), ('assessment', 'Beurteilung'), ('behaviour', 'Verhalten / Disziplin'), ('other', 'Sonstiges')], max_length=20, verbose_name='Auslöser')),
                ('date', models.DateField(verbose_name='Datum der Maßnahme')),
                ('description', models.TextField(verbose_name='Beschreibung / Gesprächsinhalt')),
                ('agreement', models.TextField(blank=True, verbose_name='Getroffene Vereinbarungen')),
                ('followup_date', models.DateField(blank=True, null=True, verbose_name='Frist / Folgetermin')),
                ('status', models.CharField(choices=[('open', 'Offen'), ('in_progress', 'In Bearbeitung'), ('closed', 'Abgeschlossen'), ('escalated', 'Eskaliert')], default='open', max_length=20, verbose_name='Status')),
                ('outcome', models.TextField(blank=True, verbose_name='Ergebnis / Abschlussbemerkung')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Abgeschlossen am')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions_closed', to=settings.AUTH_USER_MODEL, verbose_name='Abgeschlossen von')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('follow_up', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predecessor', to='intervention.intervention', verbose_name='Folge-Maßnahme')),
                ('participants', models.ManyToManyField(blank=True, help_text='Weitere Personen, die an der Maßnahme beteiligt waren.', related_name='interventions_as_participant', to=settings.AUTH_USER_MODEL, verbose_name='Beteiligte')),
            ],
            options={
                'verbose_name': 'Maßnahme',
                'verbose_name_plural': 'Maßnahmen',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
