# Generated by Django 6.0.3 on 2026-05-03 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('absence', '0002_initial'),
        ('assessment', '0004_initial'),
        ('intervention', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='student.student', verbose_name='Nachwuchskraft'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='trigger_assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to='assessment.assessment', verbose_name='Verknüpfte Beurteilung'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='trigger_sick_leave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to='absence.sickleave', verbose_name='Verknüpfte Krankmeldung'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interventions', to='intervention.interventioncategory', verbose_name='Kategorie'),
        ),
    ]
