# Generated by Django 6.0.3 on 2026-05-03 17:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Öffentliche ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('address', models.CharField(max_length=200, verbose_name='Adresse')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
            ],
            options={
                'verbose_name': 'Wohnheim',
                'verbose_name_plural': 'Wohnheime',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoomBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Öffentliche ID')),
                ('start_date', models.DateField(verbose_name='Von')),
                ('end_date', models.DateField(verbose_name='Bis')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Grund')),
            ],
            options={
                'verbose_name': 'Zimmer-Sperrung',
                'verbose_name_plural': 'Zimmer-Sperrungen',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='DormitoryManagementProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dormitory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dormitory_management_profiles', to='dormitory.dormitory', verbose_name='Wohnheim')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dormitory_management_profile', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Hausverwaltungs-Profil',
                'verbose_name_plural': 'Hausverwaltungs-Profile',
                'db_table': 'dormitory_hausverwaltungprofile',
            },
        ),
        migrations.CreateModel(
            name='ReservationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('template_file', models.FileField(upload_to='dormitory/templates/', verbose_name='Vorlage (.docx)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('uploaded_at', models.DateTimeField(auto_now=True, verbose_name='Hochgeladen am')),
                ('dormitory', models.ForeignKey(blank=True, help_text='Leer lassen für ein allgemeines Standardschreiben (Fallback für alle Wohnheime).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_templates', to='dormitory.dormitory', verbose_name='Wohnheim')),
            ],
            options={
                'verbose_name': 'Reservierungsvorlage',
                'verbose_name_plural': 'Reservierungsvorlagen',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Öffentliche ID')),
                ('number', models.CharField(max_length=20, verbose_name='Zimmer')),
                ('capacity', models.PositiveIntegerField(default=1, verbose_name='Kapazität')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('dormitory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='dormitory.dormitory', verbose_name='Wohnheim')),
            ],
            options={
                'verbose_name': 'Zimmer',
                'verbose_name_plural': 'Zimmer',
                'ordering': ['dormitory', 'number'],
            },
        ),
        migrations.CreateModel(
            name='RoomAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Öffentliche ID')),
                ('start_date', models.DateField(verbose_name='Einzugsdatum')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Auszugsdatum')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('paperless_confirmation_id', models.PositiveIntegerField(blank=True, help_text='Paperless-Dokument-ID der generierten Reservierungsbestätigung.', null=True, verbose_name='Paperless-Bestätigungs-ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='dormitory.room', verbose_name='Zimmer')),
            ],
            options={
                'verbose_name': 'Zimmerbelegung',
                'verbose_name_plural': 'Zimmerbelegungen',
                'ordering': ['-start_date'],
            },
        ),
    ]
