# Generated by Django 6.0.3 on 2026-05-03 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dormitory', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomassignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_assignments', to='student.student', verbose_name='Nachwuchskraft'),
        ),
        migrations.AddField(
            model_name='roomblock',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='dormitory.room', verbose_name='Zimmer'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('dormitory', 'number')},
        ),
    ]
