# Generated by Django 6.0.3 on 2026-05-14 17:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Eindeutiger technischer Bezeichner, z.B. „vacation_request". Wird vom Modul-Code referenziert und darf nach Anlage nicht mehr geändert werden.', max_length=64, unique=True, verbose_name='Code')),
                ('name', models.CharField(help_text='Sprechender Name, der im Admin und in Benachrichtigungen erscheint.', max_length=200, verbose_name='Bezeichnung')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('is_active', models.BooleanField(default=True, help_text='Inaktive Workflows starten keine neuen Instanzen. Laufende Instanzen werden nach altem Stand abgearbeitet.', verbose_name='Aktiv')),
                ('pre_condition', models.CharField(blank=True, help_text='Optionaler Ausdruck. Wenn gesetzt und falsch beim Start, wird die Instanz sofort als genehmigt markiert (Approval übersprungen). Beispiele: „initiator.announcement_requires_approval", „target.duration > 14".', max_length=500, verbose_name='Vorbedingung')),
                ('reject_behavior', models.CharField(choices=[('final', 'Endgültig abgelehnt'), ('to_first', 'Zurück auf erste Stufe (History bleibt)'), ('to_initiator', 'Zurück an Antragsteller zur Überarbeitung')], default='final', max_length=20, verbose_name='Verhalten bei Ablehnung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Workflow-Definition',
                'verbose_name_plural': 'Workflow-Definitionen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Niedrigste Zahl = erste Stufe.', verbose_name='Reihenfolge')),
                ('name', models.CharField(help_text='z.B. „Prüfung durch Ausbildungsreferat".', max_length=200, verbose_name='Stufen-Name')),
                ('approver_type', models.CharField(choices=[('role', 'Rolle'), ('user', 'Bestimmter Benutzer'), ('dynamic', 'Dynamisch (kontextabhängig)'), ('external_token', 'Externer Token-Approver'), ('info', 'Info-Step (nicht blockierend)')], max_length=20, verbose_name='Approver-Typ')),
                ('approver_value', models.CharField(blank=True, help_text='Kontextabhängig: Rollen-Name (z.B. „training_office"), User-PK, Resolver-Code für „dynamisch", oder leer für „info".', max_length=200, verbose_name='Approver-Wert')),
                ('deadline_days', models.PositiveIntegerField(blank=True, help_text='Nach dieser Anzahl Tagen wird das Timeout-Verhalten ausgelöst. Leer = keine Frist.', null=True, verbose_name='Frist in Tagen')),
                ('on_timeout', models.CharField(choices=[('remind', 'Nur Erinnerung'), ('escalate_next', 'Auf nächste Stufe eskalieren'), ('escalate_to', 'An bestimmten Approver eskalieren'), ('auto_approve', 'Automatisch genehmigen'), ('auto_reject', 'Automatisch ablehnen')], default='remind', max_length=20, verbose_name='Bei Fristablauf')),
                ('escalate_to_value', models.CharField(blank=True, help_text='Nur bei „escalate_to": Rollen-Code des Eskalations-Approvers (z.B. „training_director").', max_length=200, verbose_name='Eskalations-Ziel')),
                ('skip_condition', models.CharField(blank=True, help_text='Wenn gesetzt und wahr, wird diese Stufe automatisch übersprungen.', max_length=500, verbose_name='Übersprungs-Bedingung')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflow.workflowdefinition')),
            ],
            options={
                'verbose_name': 'Workflow-Stufe',
                'verbose_name_plural': 'Workflow-Stufen',
                'ordering': ['workflow', 'order'],
                'unique_together': {('workflow', 'order')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Öffentliche ID')),
                ('target_id', models.PositiveIntegerField(verbose_name='Ziel-ID')),
                ('status', models.CharField(choices=[('in_progress', 'Läuft'), ('approved', 'Genehmigt'), ('rejected', 'Abgelehnt'), ('cancelled', 'Storniert')], default='in_progress', max_length=20, verbose_name='Status')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Gestartet am')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Beendet am')),
                ('current_step_started_at', models.DateTimeField(auto_now_add=True, help_text='Wird bei jedem Stufenwechsel aktualisiert. Basis für Frist-Berechnung.', verbose_name='Aktuelle Stufe seit')),
                ('revision', models.PositiveSmallIntegerField(default=1, help_text='Zählt hoch, wenn ein abgelehnter Antrag erneut eingereicht wird.', verbose_name='Revision')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='workflow.workflowdefinition', verbose_name='Workflow-Definition')),
                ('initiator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_instances_initiated', to=settings.AUTH_USER_MODEL, verbose_name='Antragsteller:in')),
                ('target_ct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Ziel-Modell')),
                ('current_step', models.ForeignKey(blank=True, help_text='Null, wenn Workflow beendet ist.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_instances', to='workflow.workflowstep', verbose_name='Aktuelle Stufe')),
            ],
            options={
                'verbose_name': 'Workflow-Instanz',
                'verbose_name_plural': 'Workflow-Instanzen',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveSmallIntegerField(default=1, verbose_name='Revision')),
                ('actor_name', models.CharField(blank=True, help_text='Klartext für externe (Token-)Approver oder Systemaktionen.', max_length=200, verbose_name='Aktor-Name')),
                ('action', models.CharField(choices=[('submit', 'Eingereicht'), ('approve', 'Genehmigt'), ('reject', 'Abgelehnt'), ('cancel', 'Storniert'), ('remind', 'Erinnerung versandt'), ('escalate', 'Eskaliert'), ('auto_approve', 'Automatisch genehmigt'), ('auto_reject', 'Automatisch abgelehnt'), ('acknowledge', 'Zur Kenntnis genommen'), ('resubmit', 'Erneut eingereicht')], max_length=20, verbose_name='Aktion')),
                ('comment', models.TextField(blank=True, verbose_name='Kommentar')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Zeitpunkt')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_actions', to=settings.AUTH_USER_MODEL, verbose_name='Aktor:in')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='workflow.workflowinstance')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transitions', to='workflow.workflowstep', verbose_name='Stufe')),
            ],
            options={
                'verbose_name': 'Workflow-Transition',
                'verbose_name_plural': 'Workflow-Transitions',
                'ordering': ['instance', 'timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveSmallIntegerField(default=1)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='workflow.workflowinstance')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='workflow.workflowstep')),
            ],
            options={
                'verbose_name': 'Workflow-Erinnerung',
                'verbose_name_plural': 'Workflow-Erinnerungen',
                'ordering': ['-sent_at'],
                'unique_together': {('instance', 'step', 'revision')},
            },
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['target_ct', 'target_id'], name='workflow_wo_target__09ad4a_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['status', 'current_step'], name='workflow_wo_status_426de6_idx'),
        ),
    ]
